root = 'D:\AI_storage\spillover\nimby_re_fig_inputs';
code_dir = fullfile(root, 'ham_code');
addpath(code_dir);
rehash;

run_annual_political_transition_fail_safe( ...
    'RunTag', 'local_obn006_T80_0505c', ...
    'TSchedule', [80], ...
    'PeriodIter', 4, ...
    'LaggedPassThrough', false, ...
    'PassThroughLagYears', 1, ...
    'AgeWeightVariant', 'baseline', ...
    'PressureMode', 'smooth', ...
    'VoteRule', 'smooth_logit', ...
    'VoteTau', NaN, ...
    'VoteSigma', 0, ...
    'SourceMat', fullfile(root, 'old_paper_source_min.mat'), ...
    'DemographicScenario', 'published_baby_boom', ...
    'DemographicPathMat', fullfile(root, 'irfs_100.mat'), ...
    'DemographicPathVar', 'ageimpulse', ...
    'DemographicShockAmplitude', 0.25, ...
    'VoteScale', 0.02, ...
    'Candidates', [0, -0.006, 1.00], ...
    'ModIrfDir', 'D:\research_data\zac_and_david\Code\SteadyState\Copy_of_Mod_IRF', ...
    'ModFunctionsDir', 'D:\SteadyState\Mod_Functions', ...
    'CompeconDir', 'C:\Users\Dave_\COMPECON');
