function run_t80_accepted_promotion_0509(varargin)
% Promote an accepted T20 branch to T80 from the exact winning outer iterate.

p = inputParser;
p.addParameter('RunTag', 'accepted_t80');
p.addParameter('SourceRunTag', '');
p.addParameter('SourceOuter', NaN);
p.addParameter('VoteShiftMode', 'finite_horizon');
p.addParameter('VoteShiftHorizon', 5);
p.addParameter('VoteBlockLength', 4);
p.addParameter('BasisDim', 8);
p.addParameter('OuterIter', 22);
p.addParameter('BroydenDamping', 0.22);
p.addParameter('BroydenStepCap', 0.0022);
p.addParameter('BasisStepCap', 0.00032);
p.addParameter('RunRoot', fileparts(pwd));
p.parse(varargin{:});
cfg = p.Results;

if strlength(string(cfg.SourceRunTag)) == 0 || isnan(cfg.SourceOuter)
    error('SourceRunTag and SourceOuter are required.');
end

annual_dir = pwd;
out_root = fullfile(annual_dir, 'truth', 'annual_political_full_re_price_path');
source_paths = fullfile(out_root, cfg.SourceRunTag, 'paths_all.csv');
if ~isfile(source_paths)
    error('Source paths not found: %s', source_paths);
end

paths = readtable(source_paths);
paths = paths(paths.outer_iter == cfg.SourceOuter, :);
paths = sortrows(paths, 'period');
if isempty(paths)
    error('No outer_iter == %.0f rows found in %s', cfg.SourceOuter, source_paths);
end

seed_dir = fullfile(out_root, 't80_seeds');
if ~exist(seed_dir, 'dir')
    mkdir(seed_dir);
end
seed_path = fullfile(seed_dir, sprintf('%s_from_%s_o%.0f_seed.csv', cfg.RunTag, cfg.SourceRunTag, cfg.SourceOuter));
writetable(table(paths.price_generated, 'VariableNames', {'price'}), seed_path);
fprintf('T80 promotion seed written: %s\n', seed_path);

run_annual_political_full_re_price_path( ...
    'RunTag', cfg.RunTag, ...
    'T', 80, ...
    'TailYears', 20, ...
    'TerminalAnchor', 'terminal_fixed_point', ...
    'TerminalIter', 160, ...
    'TerminalRelaxation', 0.12, ...
    'TerminalBlendWeight', 1.00, ...
    'OuterIter', cfg.OuterIter, ...
    'PathRelaxation', 0.02, ...
    'PathUpdateMethod', 'basis_broyden', ...
    'BasisDim', cfg.BasisDim, ...
    'BasisDamping', 0.25, ...
    'BasisStepCap', cfg.BasisStepCap, ...
    'BasisRidge', 1e-8, ...
    'BasisEndWeight', 10, ...
    'BasisTailWeight', 0.12, ...
    'BasisFocusStart', 6, ...
    'BasisFocusEnd', 8, ...
    'BasisFocusWeight', 8, ...
    'BroydenDamping', cfg.BroydenDamping, ...
    'BroydenStepCap', cfg.BroydenStepCap, ...
    'PoliticalPassThrough', -0.006, ...
    'VoteScale', 0.02, ...
    'VoteRule', 'smooth_logit', ...
    'VoteTau', NaN, ...
    'VoteSigma', 0, ...
    'VoteShiftMode', cfg.VoteShiftMode, ...
    'VoteShiftHorizon', cfg.VoteShiftHorizon, ...
    'VoteBlockLength', cfg.VoteBlockLength, ...
    'SourceMat', fullfile(cfg.RunRoot, 'SteadyState', 'Mod_IRF', 'old_paper_source_min.mat'), ...
    'DemographicScenario', 'published_baby_boom', ...
    'DemographicPathMat', fullfile(cfg.RunRoot, 'SteadyState', 'Mod_IRF', 'irfs_100.mat'), ...
    'DemographicPathVar', 'ageimpulse', ...
    'DemographicShockAmplitude', 0.25, ...
    'ReferenceYear', NaN, ...
    'InitialPathCsv', seed_path, ...
    'ModIrfDir', fullfile(cfg.RunRoot, 'SteadyState', 'Mod_IRF'), ...
    'ModFunctionsDir', fullfile(cfg.RunRoot, 'SteadyState', 'Mod_Functions'), ...
    'CompeconDir', fullfile(cfg.RunRoot, 'COMPECON'));
end
