function ranges = annual_wealth_target_ranges()
% annual_wealth_target_ranges.m
%
% Age-profile balance-sheet share targets for the annual ownership /
% balance-sheet branch. These use official SCF age tables and focus on
% share objects the normalized model can speak to directly.

ranges = struct();
ranges.policy = "scf_balance_sheet_share_targets";
ranges.read = [
    "Use debt-holder shares and mortgaged-owner shares as the main SCF balance-sheet targets."; ...
    "These are cleaner than raw wealth-to-income levels in the normalized steady-state model."; ...
    "Map Less than 35 to the model's 25-34 entrant block."; ...
    "Treat 45-54 and 55-64 as validation unless the young-entry fit gets much closer."; ...
    "Mortgaged-owner share is proxied in the model with owner mass at negative b." ...
    ];

ranges.support = [ ...
    make_target( ...
        "debt_holder_share_under_35", ...
        "support_balance_sheet", ...
        "share", ...
        0.81911026, ...
        0.70812982, ...
        0.94688178, ...
        "Federal Reserve SCF age have-table, pooled 2016, 2019, 2022", ...
        "Young-household debt participation support target."), ...
    make_target( ...
        "debt_holder_share_35_44", ...
        "support_balance_sheet", ...
        "share", ...
        0.86936915, ...
        0.77623125, ...
        0.96053997, ...
        "Federal Reserve SCF age have-table, pooled 2016, 2019, 2022", ...
        "Family-years debt participation support target."), ...
    make_target( ...
        "mortgaged_owner_share_under_35", ...
        "support_balance_sheet", ...
        "share", ...
        0.30581140, ...
        0.25457971, ...
        0.36435079, ...
        "Federal Reserve SCF age home-secured-debt have-table, pooled 2016, 2019, 2022", ...
        "Young leveraged-owner support target."), ...
    make_target( ...
        "mortgaged_owner_share_35_44", ...
        "support_balance_sheet", ...
        "share", ...
        0.52256472, ...
        0.45076677, ...
        0.59056913, ...
        "Federal Reserve SCF age home-secured-debt have-table, pooled 2016, 2019, 2022", ...
        "Family-years leveraged-owner support target.") ...
    ];

ranges.validation = [ ...
    make_target( ...
        "mortgaged_owner_share_45_54", ...
        "validation_balance_sheet", ...
        "share", ...
        0.54398458, ...
        0.48167640, ...
        0.61229201, ...
        "Federal Reserve SCF age home-secured-debt have-table, pooled 2016, 2019, 2022", ...
        "Midlife leveraged-owner validation target."), ...
    make_target( ...
        "mortgaged_owner_share_55_64", ...
        "validation_balance_sheet", ...
        "share", ...
        0.47879443, ...
        0.41600741, ...
        0.53929042, ...
        "Federal Reserve SCF age home-secured-debt have-table, pooled 2016, 2019, 2022", ...
        "Older-age leveraged-owner validation target.") ...
    ];
end

function target = make_target(name, role, unit, reference, lower, upper, source, comment)
target = struct( ...
    'name', string(name), ...
    'role', string(role), ...
    'unit', string(unit), ...
    'reference', reference, ...
    'lower', lower, ...
    'upper', upper, ...
    'source', string(source), ...
    'comment', string(comment));
end
