function ranges = annual_homeownership_target_ranges()
% annual_homeownership_target_ranges.m
%
% Very loose support targets for annual owner occupancy by age bucket.
% These come from the U.S. Census ACS 1-year table B25007 ("Tenure by Age
% of Householder"), pooled over 2019 and 2021-2024. They are intentionally
% wide because the data object is age of householder while the model state
% is female age.

ranges = struct();
ranges.policy = "very_loose_support_bands";
ranges.read = [
    "Use these as support targets, not anchor targets."; ...
    "Only score the 25-54 bins."; ...
    "Treat 55-64 and 65-74 as validation-only."; ...
    "These are ACS age-of-householder objects, not exact female-age moments."; ...
    "Exclude 2020 from the pooled reference because there is no standard ACS 1-year release." ...
    ];

ranges.support = [ ...
    make_target( ...
        "owner_share_25_34", ...
        "support_homeownership", ...
        "share", ...
        0.4074, ...
        0.28, ...
        0.54, ...
        "US Census ACS 1-year table B25007, pooled 2019 and 2021-2024", ...
        "Young-adult owner occupancy support target with intentionally wide band."), ...
    make_target( ...
        "owner_share_35_44", ...
        "support_homeownership", ...
        "share", ...
        0.6050, ...
        0.48, ...
        0.72, ...
        "US Census ACS 1-year table B25007, pooled 2019 and 2021-2024", ...
        "Family-years owner occupancy support target with intentionally wide band."), ...
    make_target( ...
        "owner_share_45_54", ...
        "support_homeownership", ...
        "share", ...
        0.6963, ...
        0.58, ...
        0.80, ...
        "US Census ACS 1-year table B25007, pooled 2019 and 2021-2024", ...
        "Midlife owner occupancy support target with intentionally wide band.") ...
    ];

ranges.validation = [ ...
    make_target( ...
        "owner_share_55_64", ...
        "validation_homeownership", ...
        "share", ...
        0.7533, ...
        0.64, ...
        0.84, ...
        "US Census ACS 1-year table B25007, pooled 2019 and 2021-2024", ...
        "Older-age validation target only."), ...
    make_target( ...
        "owner_share_65_74", ...
        "validation_homeownership", ...
        "share", ...
        0.7922, ...
        0.70, ...
        0.87, ...
        "US Census ACS 1-year table B25007, pooled 2019 and 2021-2024", ...
        "Older-age validation target only.") ...
    ];
end

function target = make_target(name, role, unit, reference, lower, upper, source, comment)
target = struct( ...
    'name', string(name), ...
    'role', string(role), ...
    'unit', string(unit), ...
    'reference', reference, ...
    'lower', lower, ...
    'upper', upper, ...
    'source', string(source), ...
    'comment', string(comment));
end
