function export_nimby_baby_boom_reference_main()
project_root = fileparts(fileparts(mfilename('fullpath')));
out_dir = fullfile(project_root, 'notes', 'build');
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

ensure_external_matlab_data_paths();
source_file = resolve_irf_file(project_root);
s = load(source_file, ...
    'averageage', 'boom', 'Pstars_smoothed', 'homeownership_25_35_smoothed', ...
    'homeownership_55_65_smoothed', 'homeownership_smoothed', ...
    'homeownership_boom_smoothed', 'homeownership_child_smoothed', ...
    'homeownership_parent_smoothed', 'networth_boom_smoothed', ...
    'networth_child_smoothed', 'networth_parent_smoothed', ...
    'consumption_boom_smoothed', 'consumption_child_smoothed', ...
    'consumption_parent_smoothed', 'housing_boom_smoothed', ...
    'housing_child_smoothed', 'housing_parent_smoothed', 'param');

t = (0:(numel(s.averageage) - 1))';
birthrate_index = flipud(s.boom(:));
average_age = s.averageage(:);
average_age_dev = average_age - average_age(1);
house_price_index = 1 + 3 * (s.Pstars_smoothed(:) ./ s.param.Ph_ss - 1);
house_price_dev = house_price_index - house_price_index(1);
young_homeownership = s.homeownership_25_35_smoothed(:) + 0.35;
young_homeownership_dev = young_homeownership - young_homeownership(1);
old_homeownership = s.homeownership_55_65_smoothed(:);
old_homeownership_dev = old_homeownership - old_homeownership(1);
aggregate_homeownership = s.homeownership_smoothed(:);
aggregate_homeownership_dev = aggregate_homeownership - aggregate_homeownership(1);

tbl = table(t, birthrate_index, average_age, average_age_dev, house_price_index, house_price_dev, ...
    young_homeownership, young_homeownership_dev, old_homeownership, old_homeownership_dev, ...
    aggregate_homeownership, aggregate_homeownership_dev, ...
    'VariableNames', {'t', 'birthrate_index', 'average_age', 'average_age_dev', ...
    'house_price_index', 'house_price_dev', 'young_homeownership', 'young_homeownership_dev', ...
    'old_homeownership', 'old_homeownership_dev', 'aggregate_homeownership', ...
    'aggregate_homeownership_dev'});

writetable(tbl, fullfile(out_dir, 'nimby_baby_boom_reference.csv'));

tbl_full = table(t, birthrate_index, average_age, average_age_dev, house_price_index, ...
    house_price_dev, young_homeownership, young_homeownership_dev, old_homeownership, ...
    old_homeownership_dev, aggregate_homeownership, aggregate_homeownership_dev, ...
    s.homeownership_boom_smoothed(:), s.homeownership_child_smoothed(:), ...
    s.homeownership_parent_smoothed(:), s.networth_boom_smoothed(:), ...
    s.networth_child_smoothed(:), s.networth_parent_smoothed(:), ...
    s.consumption_boom_smoothed(:), s.consumption_child_smoothed(:), ...
    s.consumption_parent_smoothed(:), s.housing_boom_smoothed(:), ...
    s.housing_child_smoothed(:), s.housing_parent_smoothed(:), ...
    'VariableNames', {'t', 'birthrate_index', 'average_age', 'average_age_dev', ...
    'house_price_index', 'house_price_dev', 'young_homeownership', ...
    'young_homeownership_dev', 'old_homeownership', 'old_homeownership_dev', ...
    'aggregate_homeownership', 'aggregate_homeownership_dev', ...
    'boom_generation_homeownership_index', 'child_generation_homeownership_index', ...
    'parent_generation_homeownership_index', 'boom_generation_networth_index', ...
    'child_generation_networth_index', 'parent_generation_networth_index', ...
    'boom_generation_consumption_index', 'child_generation_consumption_index', ...
    'parent_generation_consumption_index', 'boom_generation_housing_index', ...
    'child_generation_housing_index', 'parent_generation_housing_index'});

writetable(tbl_full, fullfile(out_dir, 'nimby_baby_boom_reference_full.csv'));

meta_path = fullfile(out_dir, 'nimby_baby_boom_reference_source.txt');
fid = fopen(meta_path, 'w');
fprintf(fid, '%s\n', source_file);
fclose(fid);
end

function source_file = resolve_irf_file(project_root)
repo_candidate = fullfile(fileparts(project_root), '02_nimbyism_and_housing_supply', 'code', 'steadystate', 'Mod_IRF', 'irfs_smoothed.mat');
if exist(repo_candidate, 'file')
    source_file = repo_candidate;
    return;
end

source_file = resolve_zac_david_external_path('Code', 'SteadyState', 'Mod_IRF', 'irfs_smoothed.mat');
end
