function spec = fertility_annual_transition_path_branch_spec()
% fertility_annual_transition_path_branch_spec.m
%
% Concrete scaffold for the annual transition-path branch. This is not a
% full transition solver. It defines the time-zero cross-sectional objects
% the next annual extension should target once the steady-state mortgage /
% entrant-mixture branch has been exhausted.

annual_cfg = fertility_benchmark_annual_config();
steady_spec = fertility_annual_ownership_balance_sheet_branch_spec();
homeownership_targets = annual_homeownership_target_ranges();
wealth_targets = annual_wealth_target_ranges();

spec = struct();
spec.branch_name = "annual_transition_path_age_cross_section";
spec.date = "2026-04-05";
spec.objective = [ ...
    "Reopen the annual branch with an explicit time-zero cross section by age, " ...
    + "rather than asking the steady-state entrant mixture to generate the full " ...
    + "young leverage distribution on its own."];

spec.starting_point = struct( ...
    'label', "recentered annual no-mix baseline", ...
    'source_note', "notes/build/fertility_annual_ownership_balance_sheet_screen.md", ...
    'source_csv', "notes/build/fertility_annual_ownership_balance_sheet_screen_candidates.csv", ...
    'fertility_anchor_label', steady_spec.anchor.label, ...
    'eval_price', annual_cfg.eval_price, ...
    'price_grid', steady_spec.grids.crossing_price_grid);

spec.time_zero_targets = struct( ...
    'homeownership', homeownership_targets, ...
    'wealth', wealth_targets);

spec.time_zero_age_blocks = [ ...
    "25-34", ...
    "35-44", ...
    "45-54", ...
    "55-64"];

spec.time_zero_buckets = [ ...
    "renter_no_debt", ...
    "renter_with_debt", ...
    "owner_with_mortgage", ...
    "owner_outright"];

spec.required_objects = [ ...
    "Age-specific owner-share masses at t=0", ...
    "Age-specific debt-holder shares at t=0", ...
    "Age-specific mortgaged-owner shares at t=0", ...
    "A mapping from the observed t=0 cross section into the model state grids", ...
    "A transition run that starts from the t=0 cross section and then evolves endogenously"];

spec.implementation_phases = [ ...
    "Phase 1: construct a reduced-form time-zero age cross section using ACS owner shares and SCF debt / mortgaged-owner shares.", ...
    "Phase 2: map those age-block targets into model state buckets (renter with and without debt, owner with mortgage, owner outright).", ...
    "Phase 3: add an override path that bypasses the stationary initial density and injects the time-zero cross section instead.", ...
    "Phase 4: simulate a constant-price relaxation path first, then a price-shock path, before changing the voting block."];

spec.stop_rules = [ ...
    "Do not treat the reduced-form transition bridge as a substitute for the actual household solver.", ...
    "Do not overwrite the life-cycle law of motion after t=0; only the initial cross section should be exogenous.", ...
    "Do not start a full transition-path estimation loop before the time-zero mapping note is written and the state buckets are explicit."];

spec.templates = struct( ...
    'steady_state_anchor', "code/fertility_annual_ownership_balance_sheet_branch_spec.m", ...
    'current_transition_bridge', "code/nimby_fertility_transition_bridge.py", ...
    'homeownership_targets', "code/annual_homeownership_target_ranges.m", ...
    'wealth_targets', "code/annual_wealth_target_ranges.m");
end
