function spec = fertility_annual_ownership_balance_sheet_branch_spec()
% fertility_annual_ownership_balance_sheet_branch_spec.m
%
% Minimal structural reopen path for the annual fertility branch after the
% transition-orientation fix. This is not a full solver rewrite. It fixes
% the current usable fertility anchor and defines the next ownership /
% balance-sheet screen in a way that is consistent with the current codebase.

cfg = fertility_benchmark_annual_config();

spec = struct();
spec.branch_name = "annual_ownership_balance_sheet";
spec.date = "2026-04-05";
spec.objective = [ ...
    "Recover a stable annual vote crossing in the current confirm-era " ...
    + "fertility region by adding entrant ownership / balance-sheet " ...
    + "heterogeneity rather than another scalar wedge."];

spec.anchor = struct( ...
    'label', "confirm-era annual fertility anchor", ...
    'birth_utility_by_parity', [1.480, 1.600, 1.530], ...
    'child_utility', 0.025, ...
    'birth_cost', 0.045, ...
    'birth_price_coeff', 0.16, ...
    'lambda_crowd', 0.10, ...
    'housingmax', 15.0, ...
    'theta_r', 0.70, ...
    'CC', cfg.overrides.CC, ...
    'owner_mortgage_CC', 0.97, ...
    'owner_mortgage_spread', 0.40 * cfg.overrides.rspread, ...
    'owner_mortgage_amortization', 0.02, ...
    'owner_entry_age_max', 44, ...
    'baseline_owner_entry_b_floor', -1e9, ...
    'baseline_owner_entry_mortgage_floor', 0.35, ...
    'owner_entry_mortgage_age_max', 44, ...
    'baseline_owner_entry_payment_to_income_cap', 0.40, ...
    'owner_entry_payment_to_income_age_max', 44, ...
    'ka', cfg.overrides.ka, ...
    'rent_markup', 0.01, ...
    'baseline_initial_b_points', [-1.0, 0.0, 1.0], ...
    'baseline_initial_b_shares', [0.25, 0.50, 0.25], ...
    'constrained_initial_b_points', [-4.0, -1.5, 0.0], ...
    'constrained_initial_b_shares', [0.50, 0.35, 0.15], ...
    'helped_initial_b_base_points', [0.0, 0.5, 1.5], ...
    'helped_initial_b_shares', [0.30, 0.45, 0.25], ...
    'first_birth_realized_weights', repelem([1.00, 0.27, 0.045, 0.010], 5), ...
    'target_read', struct( ...
        'mean_age_first_birth', 30.09, ...
        'share_first_birth_30_plus', 0.521, ...
        'childless_share_at_50', 0.233));

spec.grids = struct( ...
    'eval_price', cfg.eval_price, ...
    'screen_price_grid', [1.50, 1.75, 2.00, 2.25, 2.50], ...
    'crossing_price_grid', [1.50, 1.75, 2.00, 2.25, 2.50, 3.00, 3.50, 4.00, 5.00], ...
    'support_homeownership_bins', ["25-34", "35-44", "45-54"]);

spec.fertility_target_ranges = cfg.target_ranges;
spec.homeownership_target_ranges = cfg.homeownership_target_ranges;
spec.wealth_target_ranges = cfg.wealth_target_ranges;

spec.templates = struct( ...
    'mixture_runner', "code/run_fertility_annual_latent_entry_type_smoke.m", ...
    'owner_block_template', "code/run_nimby_annual_low_entry_vote_followup.m", ...
    'homeownership_scoring', "code/score_annual_homeownership_support_targets.m", ...
    'homeownership_targets', "code/annual_homeownership_target_ranges.m", ...
    'wealth_scoring', "code/score_annual_wealth_support_targets.m", ...
    'wealth_targets', "code/annual_wealth_target_ranges.m");

spec.dead_ends = [ ...
    "pure d_a_price shifts", ...
    "parental_transfer_only", ...
    "family_space_penalty_only", ...
    "family_rent_wedge_only", ...
    "tiny owner-side scalar boxes"];

families = repmat(struct( ...
    'label', "", ...
    'description', "", ...
    'constrained_share_grid', [], ...
    'helped_share_grid', [], ...
    'constrained_housingmax_grid', [], ...
    'helped_housingmax_grid', [], ...
    'constrained_theta_r_grid', [], ...
    'helped_theta_r_grid', [], ...
    'constrained_cc_grid', [], ...
    'helped_cc_grid', [], ...
    'constrained_owner_entry_b_floor_grid', [], ...
    'helped_owner_entry_b_floor_grid', [], ...
    'constrained_owner_entry_mortgage_floor_grid', [], ...
    'helped_owner_entry_mortgage_floor_grid', [], ...
    'constrained_owner_entry_payment_to_income_cap_grid', [], ...
    'helped_owner_entry_payment_to_income_cap_grid', [], ...
    'helped_parental_transfer_share_grid', [], ...
    'helped_parental_transfer_b_boost_grid', [], ...
    'ka_grid', [], ...
    'rent_markup_grid', []), 2, 1);

families(1) = struct( ...
    'label', "two_type_constrained_vs_helped_entry", ...
    'description', [ ...
        "Small exogenous entrant mix. One type is ownership constrained " ...
        + "through a tighter owner grid, lower renter efficiency, and a " ...
        + "poorer entry asset distribution; the other is a helped-entry " ...
        + "type with deposit-style entry support plus easier owner access " ...
        + "and looser mortgage access " ...
        + "and a less disadvantaged renter margin."], ...
    'constrained_share_grid', [0.10, 0.20, 0.30], ...
    'helped_share_grid', [0.10, 0.20, 0.30], ...
    'constrained_housingmax_grid', [10.0, 12.0], ...
    'helped_housingmax_grid', [15.0, 18.0], ...
    'constrained_theta_r_grid', [0.35, 0.40, 0.45], ...
    'helped_theta_r_grid', [0.70, 0.85], ...
    'constrained_cc_grid', [0.90, 0.96, 0.97], ...
    'helped_cc_grid', [0.97, 0.99], ...
    'constrained_owner_entry_b_floor_grid', [1.0, 2.0, 3.0], ...
    'helped_owner_entry_b_floor_grid', [-1.0, 0.0, 0.5], ...
    'constrained_owner_entry_mortgage_floor_grid', [0.35, 0.50], ...
    'helped_owner_entry_mortgage_floor_grid', [0.20, 0.35], ...
    'constrained_owner_entry_payment_to_income_cap_grid', [0.30, 0.35], ...
    'helped_owner_entry_payment_to_income_cap_grid', [0.40, 0.45], ...
    'helped_parental_transfer_share_grid', [1.0], ...
    'helped_parental_transfer_b_boost_grid', [1.0, 2.0, 3.0], ...
    'ka_grid', [cfg.overrides.ka, cfg.ka_five_year], ...
    'rent_markup_grid', [cfg.overrides.rent_markup, 0.01]);

families(2) = struct( ...
    'label', "three_type_constrained_base_helped_entry", ...
    'description', [ ...
        "Same ownership / balance-sheet idea, but keep a middle baseline " ...
        + "type alive with its own middle entry asset distribution so the " ...
        + "screen does not force all entrants to be " ...
        + "either constrained or fully helped, while still allowing mortgage-access dispersion."], ...
    'constrained_share_grid', [0.10, 0.15, 0.20], ...
    'helped_share_grid', [0.10, 0.15, 0.20], ...
    'constrained_housingmax_grid', [10.0, 12.0], ...
    'helped_housingmax_grid', [15.0, 18.0], ...
    'constrained_theta_r_grid', [0.35, 0.40], ...
    'helped_theta_r_grid', [0.70, 0.85], ...
    'constrained_cc_grid', [0.90, 0.96], ...
    'helped_cc_grid', [0.97, 0.99], ...
    'constrained_owner_entry_b_floor_grid', [1.0, 2.0], ...
    'helped_owner_entry_b_floor_grid', [-1.0, 0.0], ...
    'constrained_owner_entry_mortgage_floor_grid', [0.35, 0.50], ...
    'helped_owner_entry_mortgage_floor_grid', [0.20, 0.35], ...
    'constrained_owner_entry_payment_to_income_cap_grid', [0.30, 0.35], ...
    'helped_owner_entry_payment_to_income_cap_grid', [0.40, 0.45], ...
    'helped_parental_transfer_share_grid', [1.0], ...
    'helped_parental_transfer_b_boost_grid', [1.0, 2.0], ...
    'ka_grid', [cfg.overrides.ka, cfg.ka_five_year], ...
    'rent_markup_grid', [cfg.overrides.rent_markup, 0.01]);

spec.families = families;

spec.phase_order = [ ...
    "Finish the corrected annual rerun and treat all pre-fix annual screens as historical only.", ...
    "If the rerun still has no crossing, reopen annual with entrant-type ownership / balance-sheet heterogeneity around the fixed fertility anchor.", ...
    "Score candidates on fertility bands, ACS owner-share support bins, and stable unique crossing on the finer owner grid.", ...
    "Only if that steady-state branch gets close should a true transition-path branch be started."];

spec.stop_rules = [ ...
    "Do not spend more Hamilton time on one-parameter rescue screens.", ...
    "Do not promote low-resolution unique crossings that disappear on finer owner grids.", ...
    "If the type-mixture branch still cannot generate a stable crossing, stop steady-state rescue and move to a real transition-path extension."];
end
