function ranges = fertility_annual_target_ranges()
% fertility_annual_target_ranges.m
%
% Deliberately loose annual fertility screening ranges. These are intended
% for economic-model calibration screens, not simulation-style moment
% matching. Objects inside the band should be treated as acceptable; only
% gross misses outside the band should be penalized materially.

ranges = struct();
ranges.policy = "wide_screening_bands";
ranges.read = [
    "Use these as broad screening targets, not knife-edge point targets."; ...
    "Fit timing within years, not months."; ...
    "Treat the pooled 25+ first-birth timing shape as the main annual timing target."; ...
    "Use mean age and share 30+ as lighter summary checks, not the main timing pass/fail rule."; ...
    "Keep TFR as validation-only because the model object is avg_birth_rate, not literal TFR." ...
    ];

ranges.primary = [ ...
    make_target( ...
        "mean_age_first_birth", ...
        "primary", ...
        "years", ...
        27.4841, ...
        25.0, ...
        31.0, ...
        "CDC first-birth state-year pull, pooled 2020-2024", ...
        "Main annual timing anchor. Wide band by design."), ...
    make_target( ...
        "share_first_birth_30_plus", ...
        "primary", ...
        "share", ...
        0.3715, ...
        0.20, ...
        0.55, ...
        "CDC first-birth state-year pull, pooled 2020-2024", ...
        "Main timing-share anchor. Reject only clearly wrong delay patterns."), ...
    make_target( ...
        "childless_share_at_50", ...
        "primary", ...
        "share", ...
        0.1650, ...
        0.10, ...
        0.35, ...
        "US Census target plus childlessness recalibration sweep", ...
        "Stock fertility anchor. Broad enough for early-stage annual recalibration.") ...
    ];

ranges.support = [ ...
    make_target("share_first_birth_25_29", "primary_timing_shape", "share", 0.4331, 0.35, 0.52, ...
        "CDC first-birth state-year pull, pooled 2020-2024", ...
        "Moderately tight grouped-age timing-shape target around the CDC pooled reference."), ...
    make_target("share_first_birth_30_34", "primary_timing_shape", "share", 0.3805, 0.30, 0.46, ...
        "CDC first-birth state-year pull, pooled 2020-2024", ...
        "Moderately tight grouped-age timing-shape target around the CDC pooled reference."), ...
    make_target("share_first_birth_35_39", "primary_timing_shape", "share", 0.1533, 0.10, 0.22, ...
        "CDC first-birth state-year pull, pooled 2020-2024", ...
        "Moderately tight grouped-age timing-shape target around the CDC pooled reference."), ...
    make_target("share_first_birth_40_44_plus", "primary_timing_shape", "share", 0.0331, 0.02, 0.06, ...
        "CDC first-birth state-year pull, pooled 2020-2024", ...
        "Moderately tight top-bin timing-shape target; still wider than the annual CDC variation because the tail is grouped.") ...
    ];

ranges.validation = make_target( ...
    "us_total_fertility_rate", ...
    "validation", ...
    "children_per_woman", ...
    1.6446, ...
    1.40, ...
    1.95, ...
    "World Bank US TFR, pooled 2020-2023", ...
    "Validation only; do not score tightly because model birth rate is not literal TFR.");

ranges.qualitative = [ ...
    "Higher house prices should raise mean age at first birth."; ...
    "Higher house prices should raise the share of first births at age 30+."; ...
    "Higher house prices should lower average birth rates and lower fertility levels."; ...
    "Reject candidates with the wrong comparative-static signs even if some levels are inside the loose bands." ...
    ];
end

function target = make_target(name, role, unit, reference, lower, upper, source, comment)
target = struct( ...
    'name', string(name), ...
    'role', string(role), ...
    'unit', string(unit), ...
    'reference', reference, ...
    'lower', lower, ...
    'upper', upper, ...
    'source', string(source), ...
    'comment', string(comment));
end
