function run_transition_re_fertility_main(mode)
% run_transition_re_fertility_main.m
%
% Top-level short-horizon RE smoke driver for the structural five-year
% Bellman transition object.

if nargin < 1 || isempty(mode)
    mode = "smoke";
end
mode = string(mode);

project_root = fileparts(fileparts(mfilename('fullpath')));
out_dir = fullfile(project_root, 'notes', 'build');
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

cfg = fertility_benchmark_config();
[initial_q_path, overrides, options, note_suffix] = build_mode_config_local(mode, cfg);

results = solve_transition_re_fertility(initial_q_path, overrides, options);

path_table = table();
summary = results.summary;
if isstruct(summary) && isfield(summary, 'q_path') && ~isempty(summary.q_path)
    T = numel(summary.q_path);
    path_table = table( ...
        (1:T)', ...
        summary.q_path(:), ...
        summary.avg_birth_rate(:), ...
        summary.mean_age_first_birth(:), ...
        summary.owner_share_25_34(:), ...
        summary.mortgaged_owner_share_under_35(:), ...
        summary.total_mass(:), ...
        'VariableNames', {'t', 'q', 'avg_birth_rate', 'mean_age_first_birth', 'owner_share_25_34', 'mortgaged_owner_share_under_35', 'total_mass'});
end

iteration_csv = fullfile(out_dir, sprintf('structural_transition_re_%s_iterations.csv', note_suffix));
vote_csv = fullfile(out_dir, sprintf('structural_transition_re_%s_vote_grid.csv', note_suffix));
period_csv = fullfile(out_dir, sprintf('structural_transition_re_%s_periods.csv', note_suffix));
path_csv = fullfile(out_dir, sprintf('structural_transition_re_%s_path_summary.csv', note_suffix));
note_path = fullfile(out_dir, sprintf('structural_transition_re_%s.md', note_suffix));
mat_path = fullfile(out_dir, sprintf('structural_transition_re_%s_results.mat', note_suffix));

writetable(results.iteration_history, iteration_csv);
writetable(results.vote_grid_history, vote_csv);
writetable(results.period_history, period_csv);
if isempty(path_table)
    if isfile(path_csv)
        delete(path_csv);
    end
else
    writetable(path_table, path_csv);
end
save(mat_path, 'results');
write_note_local(note_path, results, overrides, note_suffix);

disp('Structural transition Bellman RE smoke complete.');
end

function [initial_q_path, overrides, options, note_suffix] = build_mode_config_local(mode, cfg)
switch lower(char(mode))
    case 'smoke'
        initial_q_path = repmat(cfg.eval_price, 1, 4);
        overrides = struct('I', 12, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.25, ...
            'tolerance', 2.0e-3, ...
            'max_iter', 4, ...
            'q_search_grid', [1.75, 2.00, 2.25], ...
            'q_refine_points', 5, ...
            'verbose_progress', true);
        note_suffix = 'smoke';
    case 'diag'
        initial_q_path = repmat(cfg.eval_price, 1, 2);
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.25, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 1, ...
            'q_search_grid', [1.75, 2.00, 2.25], ...
            'q_refine_points', 3, ...
            'verbose_progress', true);
        note_suffix = 'diag';
    case 't4_diag'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.20, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 1, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true);
        note_suffix = 't4_diag';
    case 't4_iter'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.20, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 2, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true);
        note_suffix = 't4_iter';
    case 't4_iter_debug'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.20, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 2, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false);
        note_suffix = 't4_iter_debug';
    case 't4_iter_debug3'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.20, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 3, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false);
        note_suffix = 't4_iter_debug3';
    case 't4_iter_debug3_sidecar'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.20, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 3, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_iter_debug3_sidecar';
    case 't4_step_iter_debug5_sidecar_lowdamp'
        initial_q_path = [2.0, 2.10, 2.10, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 5, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_step_iter_debug5_sidecar_lowdamp';
    case 't4_front_loaded_iter_debug5_sidecar_lowdamp'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 5, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug5_sidecar_lowdamp';
    case 't4_front_loaded_iter_debug8_sidecar_controlled'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'tolerance', 5.0e-3, ...
            'max_iter', 8, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug8_sidecar_controlled';
    case 't4_front_loaded_iter_debug12_sidecar_controlled'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'tolerance', 5.0e-3, ...
            'max_iter', 12, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug12_sidecar_controlled';
    case 't4_front_loaded_iter_debug16_sidecar_adaptive'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 16, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug16_sidecar_adaptive';
    case 't4_front_loaded_iter_debug16_sidecar_adaptive_continuity'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'root_selection_anchor', 'previous_implied', ...
            'tolerance', 5.0e-3, ...
            'max_iter', 16, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug16_sidecar_adaptive_continuity';
    case 't4_front_loaded_iter_debug16_sidecar_adaptive_p4_continuity'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'root_selection_previous_implied_mask', [false, false, false, true], ...
            'tolerance', 5.0e-3, ...
            'max_iter', 16, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug16_sidecar_adaptive_p4_continuity';
    case 't4_front_loaded_iter_debug24_sidecar_adaptive'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 24, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug24_sidecar_adaptive';
    case 't4_front_loaded_iter_debug24_sidecar_adaptive_hysteresis'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_hysteresis_mask', [false, false, false, true], ...
            'branch_hysteresis_q_tolerance', 0.20, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 24, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug24_sidecar_adaptive_hysteresis';
    case 't4_front_loaded_iter_debug24_sidecar_adaptive_tiebreak'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.01, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 24, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug24_sidecar_adaptive_tiebreak';
    case 't4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.01, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 32, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak';
    case 't4_front_loaded_iter_debug32_sidecar_adaptive_tiebreakwide'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.03, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 32, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug32_sidecar_adaptive_tiebreakwide';
    case 't4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak_rollback'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.03, ...
            'rollback_to_best_on_jump', true, ...
            'rollback_worsen_ratio', 1.50, ...
            'rollback_worsen_abs_tol', 0.05, ...
            'rollback_shrink_factor', 0.50, ...
            'max_rollbacks', 3, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 32, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak_rollback';
    case 't4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak_backtrack'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.03, ...
            'backtracking_line_search', true, ...
            'backtracking_activate_residual', 0.15, ...
            'backtracking_shrink_factor', 0.50, ...
            'backtracking_accept_worsen_ratio', 1.10, ...
            'backtracking_accept_worsen_abs_tol', 0.01, ...
            'max_backtracking_rounds', 3, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 32, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak_backtrack';
    case 't4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.03, ...
            'backtracking_line_search', true, ...
            'backtracking_activate_residual', 0.15, ...
            'backtracking_shrink_factor', 0.50, ...
            'backtracking_accept_worsen_ratio', 1.10, ...
            'backtracking_accept_worsen_abs_tol', 0.01, ...
            'max_backtracking_rounds', 3, ...
            'stop_on_backtracking_stall', true, ...
            'max_backtracking_stall_iters', 2, ...
            'backtracking_stall_q_tolerance', 1.0e-6, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 40, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall';
    case 't4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_round5'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.03, ...
            'backtracking_line_search', true, ...
            'backtracking_activate_residual', 0.15, ...
            'backtracking_shrink_factor', 0.50, ...
            'backtracking_accept_worsen_ratio', 1.10, ...
            'backtracking_accept_worsen_abs_tol', 0.01, ...
            'max_backtracking_rounds', 5, ...
            'stop_on_backtracking_stall', true, ...
            'max_backtracking_stall_iters', 2, ...
            'backtracking_stall_q_tolerance', 1.0e-6, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 40, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_round5';
    case 't4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_coordinate'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.03, ...
            'backtracking_line_search', true, ...
            'backtracking_activate_residual', 0.15, ...
            'backtracking_shrink_factor', 0.50, ...
            'backtracking_accept_worsen_ratio', 1.10, ...
            'backtracking_accept_worsen_abs_tol', 0.01, ...
            'max_backtracking_rounds', 3, ...
            'stop_on_backtracking_stall', true, ...
            'max_backtracking_stall_iters', 2, ...
            'backtracking_stall_q_tolerance', 1.0e-6, ...
            'coordinate_backtracking_line_search', true, ...
            'coordinate_backtracking_activate_residual', 0.10, ...
            'max_coordinate_backtracking_periods', 2, ...
            'coordinate_backtracking_require_improvement', true, ...
            'coordinate_backtracking_improve_tol', 0.0, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 40, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_coordinate';
    case 't4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_coordinate_p4continuity'
        initial_q_path = [2.0, 2.05, 2.08, 2.10];
        overrides = struct('I', 8, 'J', 4);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'damping_path', [0.15, 0.08, 0.10, 0.04], ...
            'max_q_update_step', [0.12, 0.07, 0.08, 0.03], ...
            'adaptive_update_control', true, ...
            'adaptive_worsen_ratio', 1.05, ...
            'adaptive_worsen_abs_tol', 0.01, ...
            'adaptive_shrink_factor', 0.75, ...
            'branch_tie_break_mask', [false, false, false, true], ...
            'branch_tie_break_q_tolerance', 0.03, ...
            'backtracking_line_search', true, ...
            'backtracking_activate_residual', 0.15, ...
            'backtracking_shrink_factor', 0.50, ...
            'backtracking_accept_worsen_ratio', 1.10, ...
            'backtracking_accept_worsen_abs_tol', 0.01, ...
            'max_backtracking_rounds', 3, ...
            'stop_on_backtracking_stall', true, ...
            'max_backtracking_stall_iters', 2, ...
            'backtracking_stall_q_tolerance', 1.0e-6, ...
            'coordinate_backtracking_line_search', true, ...
            'coordinate_backtracking_activate_residual', 0.10, ...
            'max_coordinate_backtracking_periods', 2, ...
            'max_coordinate_backtracking_rounds', 6, ...
            'coordinate_backtracking_require_improvement', true, ...
            'coordinate_backtracking_improve_tol', 0.0, ...
            'coordinate_min_damping_path', [0.0375, 0.0200, 0.0250, 0.00125], ...
            'coordinate_min_max_q_update_step', [0.0300, 0.0175, 0.0200, 0.00375], ...
            'coordinate_branch_continuity_mask', [false, false, false, true], ...
            'coordinate_branch_continuity_q_tolerance', 0.03, ...
            'tolerance', 5.0e-3, ...
            'max_iter', 40, ...
            'q_search_grid', [1.5, 2.0, 2.5], ...
            'q_refine_points', 5, ...
            'verbose_progress', true, ...
            'compute_final_summary', false, ...
            'transition_backend', 'sidecar_mex', ...
            'transition_front_row_cache', true);
        note_suffix = 't4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_coordinate_p4continuity';
    case 'medium'
        initial_q_path = repmat(cfg.eval_price, 1, 4);
        overrides = struct('I', 20, 'J', 6);
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.18, ...
            'tolerance', 7.5e-4, ...
            'max_iter', 6, ...
            'q_search_grid', 1.5:0.25:2.5, ...
            'q_refine_points', 7, ...
            'verbose_progress', true);
        note_suffix = 'medium';
    case 'benchmark'
        initial_q_path = repmat(cfg.eval_price, 1, 4);
        overrides = cfg.overrides;
        options = struct( ...
            'rbPos_path', cfg.rbPos, ...
            'damping', 0.15, ...
            'tolerance', 5.0e-4, ...
            'max_iter', 8, ...
            'q_search_grid', 1.5:0.125:2.5, ...
            'q_refine_points', 9, ...
            'verbose_progress', true);
        note_suffix = 'benchmark';
    otherwise
        error('Unknown mode "%s". Use "diag", "t4_diag", "t4_iter", "t4_iter_debug", "t4_iter_debug3", "t4_iter_debug3_sidecar", "t4_step_iter_debug5_sidecar_lowdamp", "t4_front_loaded_iter_debug5_sidecar_lowdamp", "t4_front_loaded_iter_debug8_sidecar_controlled", "t4_front_loaded_iter_debug12_sidecar_controlled", "t4_front_loaded_iter_debug16_sidecar_adaptive", "t4_front_loaded_iter_debug16_sidecar_adaptive_continuity", "t4_front_loaded_iter_debug16_sidecar_adaptive_p4_continuity", "t4_front_loaded_iter_debug24_sidecar_adaptive", "t4_front_loaded_iter_debug24_sidecar_adaptive_hysteresis", "t4_front_loaded_iter_debug24_sidecar_adaptive_tiebreak", "t4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak", "t4_front_loaded_iter_debug32_sidecar_adaptive_tiebreakwide", "t4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak_rollback", "t4_front_loaded_iter_debug32_sidecar_adaptive_tiebreak_backtrack", "t4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall", "t4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_round5", "t4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_coordinate", "t4_front_loaded_iter_debug40_sidecar_adaptive_tiebreak_backtrackstall_coordinate_p4continuity", "smoke", "medium", or "benchmark".', mode);
end
end

function write_note_local(path, results, overrides, note_suffix)
fid = fopen(path, 'w');
if fid == -1
    error('Could not write note: %s', path);
end
cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>

summary = results.summary;
history = results.iteration_history;
periods = results.period_history;

fprintf(fid, '# Structural transition Bellman RE (%s)\n\n', note_suffix);
fprintf(fid, 'This note records the first short-horizon outer fixed point for the structural five-year Bellman transition object.\n\n');
fprintf(fid, 'Setup:\n\n');
fprintf(fid, '- initial guess: `%s`\n', format_path_local(history, 'q_guess', 1));
fprintf(fid, '- grid: `I = %d`, `J = %d`\n', overrides.I, overrides.J);
fprintf(fid, '- damping: `%.3f`\n', results.options.damping);
fprintf(fid, '- tolerance: `%.3g`\n', results.options.tolerance);
fprintf(fid, '- max iterations: `%d`\n\n', results.options.max_iter);
fprintf(fid, '- transition backend: `%s`\n', char(string(results.options.transition_backend)));
fprintf(fid, '- front-row cache: `%s`\n\n', mat2str(logical(results.options.transition_front_row_cache)));
fprintf(fid, '- damping path: `%s`\n', format_numeric_path_local(results.options.damping_path));
fprintf(fid, '- max update step: `%s`\n', format_numeric_path_local(results.options.max_q_update_step));
fprintf(fid, '- root selection anchor: `%s`\n\n', char(results.options.root_selection_anchor));
if any(results.options.root_selection_previous_implied_mask)
    fprintf(fid, '- previous-implied anchor mask: `%s`\n\n', format_logical_path_local(results.options.root_selection_previous_implied_mask));
end
if any(results.options.branch_hysteresis_mask)
    fprintf(fid, '- branch hysteresis mask: `%s`\n', format_logical_path_local(results.options.branch_hysteresis_mask));
    fprintf(fid, '- branch hysteresis q tolerance: `%.3f`\n\n', results.options.branch_hysteresis_q_tolerance);
end
if any(results.options.branch_tie_break_mask)
    fprintf(fid, '- branch tie-break mask: `%s`\n', format_logical_path_local(results.options.branch_tie_break_mask));
    fprintf(fid, '- branch tie-break q tolerance: `%.3f`\n\n', results.options.branch_tie_break_q_tolerance);
end
fprintf(fid, '- adaptive outer control: `%s`\n', mat2str(logical(results.options.adaptive_update_control)));
if results.options.adaptive_update_control
    fprintf(fid, '- adaptive worsen ratio: `%.3f`\n', results.options.adaptive_worsen_ratio);
    fprintf(fid, '- adaptive worsen abs tol: `%.3f`\n', results.options.adaptive_worsen_abs_tol);
    fprintf(fid, '- adaptive shrink factor: `%.3f`\n', results.options.adaptive_shrink_factor);
    fprintf(fid, '- min damping path: `%s`\n', format_numeric_path_local(results.options.min_damping_path));
    fprintf(fid, '- min max update step: `%s`\n', format_numeric_path_local(results.options.min_max_q_update_step));
    fprintf(fid, '- final active damping path: `%s`\n', format_numeric_path_local(results.final_damping_path));
    fprintf(fid, '- final active max update step: `%s`\n\n', format_numeric_path_local(results.final_max_q_update_step));
else
    fprintf(fid, '\n');
end
if logical(results.options.backtracking_line_search)
    fprintf(fid, '- backtracking line search: `%s`\n', mat2str(logical(results.options.backtracking_line_search)));
    fprintf(fid, '- backtracking activate residual: `%.3f`\n', results.options.backtracking_activate_residual);
    fprintf(fid, '- backtracking shrink factor: `%.3f`\n', results.options.backtracking_shrink_factor);
    fprintf(fid, '- backtracking accept worsen ratio: `%.3f`\n', results.options.backtracking_accept_worsen_ratio);
    fprintf(fid, '- backtracking accept worsen abs tol: `%.3f`\n', results.options.backtracking_accept_worsen_abs_tol);
    fprintf(fid, '- max backtracking rounds: `%d`\n', results.options.max_backtracking_rounds);
    if logical(results.options.stop_on_backtracking_stall)
        fprintf(fid, '- stop on backtracking stall: `%s`\n', mat2str(logical(results.options.stop_on_backtracking_stall)));
        fprintf(fid, '- max backtracking stall iterations: `%d`\n', results.options.max_backtracking_stall_iters);
        fprintf(fid, '- backtracking stall q tolerance: `%.1e`\n', results.options.backtracking_stall_q_tolerance);
    end
    fprintf(fid, '\n');
end
if logical(results.options.coordinate_backtracking_line_search)
    fprintf(fid, '- coordinate backtracking line search: `%s`\n', mat2str(logical(results.options.coordinate_backtracking_line_search)));
    fprintf(fid, '- coordinate backtracking activate residual: `%.3f`\n', results.options.coordinate_backtracking_activate_residual);
    fprintf(fid, '- max coordinate backtracking periods: `%d`\n', results.options.max_coordinate_backtracking_periods);
    fprintf(fid, '- max coordinate backtracking rounds: `%d`\n', results.options.max_coordinate_backtracking_rounds);
    fprintf(fid, '- coordinate backtracking require improvement: `%s`\n', mat2str(logical(results.options.coordinate_backtracking_require_improvement)));
    fprintf(fid, '- coordinate backtracking improve tol: `%.6f`\n', results.options.coordinate_backtracking_improve_tol);
    if any(abs(results.options.coordinate_min_damping_path - results.options.min_damping_path) > 1.0e-12)
        fprintf(fid, '- coordinate min damping path: `%s`\n', format_numeric_path_local(results.options.coordinate_min_damping_path));
    end
    if any(abs(results.options.coordinate_min_max_q_update_step - results.options.min_max_q_update_step) > 1.0e-12)
        fprintf(fid, '- coordinate min max update step: `%s`\n', format_numeric_path_local(results.options.coordinate_min_max_q_update_step));
    end
    if any(results.options.coordinate_branch_continuity_mask)
        fprintf(fid, '- coordinate branch continuity mask: `%s`\n', format_logical_path_local(results.options.coordinate_branch_continuity_mask));
        fprintf(fid, '- coordinate branch continuity q tolerance: `%.3f`\n', results.options.coordinate_branch_continuity_q_tolerance);
    end
    fprintf(fid, '\n');
end
if logical(results.options.rollback_to_best_on_jump)
    fprintf(fid, '- rollback to best on jump: `%s`\n', mat2str(logical(results.options.rollback_to_best_on_jump)));
    fprintf(fid, '- rollback worsen ratio: `%.3f`\n', results.options.rollback_worsen_ratio);
    fprintf(fid, '- rollback worsen abs tol: `%.3f`\n', results.options.rollback_worsen_abs_tol);
    fprintf(fid, '- rollback shrink factor: `%.3f`\n', results.options.rollback_shrink_factor);
    fprintf(fid, '- max rollbacks: `%d`\n', results.options.max_rollbacks);
    fprintf(fid, '- rollbacks used: `%d`\n\n', results.rollback_count);
end

fprintf(fid, 'The path update uses the project''s existing political-support object: at each date, solve for the current `q_t` that makes the transition vote object locally cross zero while holding the later tail at the current guess.\n\n');
fprintf(fid, 'The vote perturbation currently uses a `%s` higher-price comparison path so the transition support object lines up with the steady-state permanent price-shock logic.\n\n', char(results.options.vote_dp_scope));

fprintf(fid, '## Iteration history\n\n');
fprintf(fid, '| iter | max residual | q guess | q implied |\n');
fprintf(fid, '| --- | ---: | --- | --- |\n');
for i = 1:height(history)
    fprintf(fid, '| %d | %.6f | %s | %s |\n', ...
        history.iteration(i), history.max_abs_residual(i), ...
        format_path_local(history, 'q_guess', i), format_path_local(history, 'q_implied', i));
end

fprintf(fid, '\n## Period roots on final iteration\n\n');
fprintf(fid, '| period | implied q | method | sign changes | selected vote |\n');
fprintf(fid, '| --- | ---: | --- | ---: | ---: |\n');
last_iter = max(periods.iteration);
last_rows = periods(periods.iteration == last_iter, :);
for i = 1:height(last_rows)
    fprintf(fid, '| %d | %.3f | %s | %d | %.6f |\n', ...
        last_rows.period(i), last_rows.implied_q(i), char(last_rows.root_method(i)), ...
        last_rows.sign_change_count(i), last_rows.selected_vote(i));
end

if isstruct(summary) && isfield(summary, 'q_path') && ~isempty(summary.q_path)
    fprintf(fid, '\n## Final path summary\n\n');
    fprintf(fid, '| t | q | avg birth rate | mean age first birth | owner share 25-34 | mortgaged-owner share under 35 | total mass |\n');
    fprintf(fid, '| ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n');
    for t = 1:numel(summary.q_path)
        mean_age = summary.mean_age_first_birth(t);
        if isnan(mean_age)
            mean_age_str = 'NaN';
        else
            mean_age_str = sprintf('%.3f', mean_age);
        end
        fprintf(fid, '| %d | %.3f | %.6f | %s | %.6f | %.6f | %.6f |\n', ...
            t, summary.q_path(t), summary.avg_birth_rate(t), mean_age_str, ...
            summary.owner_share_25_34(t), summary.mortgaged_owner_share_under_35(t), summary.total_mass(t));
    end
else
    fprintf(fid, '\n## Final path summary\n\n');
    fprintf(fid, '_Skipped in debug mode to avoid the extra full-path solve._\n');
end

fprintf(fid, '\n## Read\n\n');
if results.converged
    fprintf(fid, '- The short-horizon Bellman RE smoke converged within the requested tolerance.\n');
elseif isfield(results, 'stalled') && results.stalled
    fprintf(fid, '- The short-horizon Bellman RE smoke stopped early on a repeated backtracking stall before the iteration cap.\n');
else
    fprintf(fid, '- The short-horizon Bellman RE smoke did **not** hit the requested tolerance before the iteration cap.\n');
end
fprintf(fid, '- This is a smoke-stage RE object only. It is meant to test whether the transition vote-root mapping is numerically stable before any longer-horizon or benchmark-grid push.\n');
fprintf(fid, '- The equilibrium concept is still the project''s political-support crossing, now evaluated on the transition path rather than only in the steady state.\n');
fprintf(fid, '- If this path is unstable or wildly sensitive, the next step should be to tighten the transition vote mapping before extending horizon or moving to Hamilton.\n');
end

function path_label = format_path_local(history, prefix, row_idx)
names = history.Properties.VariableNames;
mask = startsWith(names, prefix + "_t");
path_values = history{row_idx, mask};
path_label = format_numeric_path_local(path_values);
end

function path_label = format_numeric_path_local(path_values)
path_values = path_values(:)';
parts = strings(1, numel(path_values));
for i = 1:numel(path_values)
    if isinf(path_values(i))
        parts(i) = "inf";
    else
        parts(i) = sprintf('%.3f', path_values(i));
    end
end
path_label = "[" + strjoin(parts, ", ") + "]";
end

function path_label = format_logical_path_local(path_values)
path_values = logical(path_values(:)');
parts = string(double(path_values));
path_label = "[" + strjoin(parts, ", ") + "]";
end
