function summary = run_transition_re_policy_bridge_band_sweep()
% Sweep narrow benchmark bands for the by-period-price policy bridge over the
% full horizon to see whether symmetric anchoring around price 2.0 restores
% stability more effectively than a floor alone.

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

demographic_path_full = build_demographic_path_from_age_state_csv(project_root);
T_full = numel(demographic_path_full.periods);
calendar_years = demographic_path_full.periods(:);

[common_guess, guess_source] = load_common_guess(this_dir, T_full);
cases = build_band_cases();
base_params = default_band_sweep_params();

summary_rows = repmat(struct( ...
    'case_name', "", ...
    'description', "", ...
    'policy_reference_price_floor', NaN, ...
    'policy_reference_price_cap', NaN, ...
    'status', "", ...
    'iterations_completed', NaN, ...
    'converged', false, ...
    'looks_stable', false, ...
    'residual_norm', NaN, ...
    'max_abs_gap', NaN, ...
    'price_min', NaN, ...
    'price_max', NaN, ...
    'policy_reference_min_used', NaN, ...
    'policy_reference_max_used', NaN, ...
    'floor_binding_periods', NaN, ...
    'cap_binding_periods', NaN, ...
    'elapsed_seconds', NaN), numel(cases), 1);

path_rows = repmat(struct( ...
    'case_name', "", ...
    'period_index', NaN, ...
    'calendar_year', NaN, ...
    'final_price', NaN, ...
    'implied_price', NaN, ...
    'policy_reference_price_used', NaN, ...
    'floor_binding', false, ...
    'cap_binding', false, ...
    'Hdemand', NaN, ...
    'Hsupply', NaN, ...
    'excess_demand', NaN), numel(cases) * T_full, 1);
path_row_idx = 0;

all_results = cell(numel(cases), 1);

fprintf('=== NIMBY RE policy-bridge band sweep ===\n');
fprintf('Warm start source: %s\n', guess_source);

for i = 1:numel(cases)
    case_spec = cases(i);
    params = base_params;
    params.transition_policy_mode = char(case_spec.transition_policy_mode);
    params.policy_reference_mode = char(case_spec.policy_reference_mode);
    params.policy_reference_price = case_spec.policy_reference_price;
    params.policy_reference_price_floor = case_spec.policy_reference_price_floor;
    params.policy_reference_price_cap = case_spec.policy_reference_price_cap;

    fprintf('\nRunning case %s ...\n', case_spec.case_name);
    case_tic = tic;
    results = solve_transition_re_no_politics(common_guess, demographic_path_full, params);
    elapsed_seconds = toc(case_tic);
    all_results{i} = results;

    policy_ref_path = results.policy_reference_price_path_used(:);
    floor_mask = false(size(policy_ref_path));
    cap_mask = false(size(policy_ref_path));
    if ~isnan(case_spec.policy_reference_price_floor)
        floor_mask = abs(policy_ref_path - case_spec.policy_reference_price_floor) < 1e-10;
    end
    if ~isnan(case_spec.policy_reference_price_cap)
        cap_mask = abs(policy_ref_path - case_spec.policy_reference_price_cap) < 1e-10;
    end

    summary_rows(i) = struct( ...
        'case_name', case_spec.case_name, ...
        'description', case_spec.description, ...
        'policy_reference_price_floor', case_spec.policy_reference_price_floor, ...
        'policy_reference_price_cap', case_spec.policy_reference_price_cap, ...
        'status', "ok", ...
        'iterations_completed', results.iterations, ...
        'converged', results.converged, ...
        'looks_stable', looks_stable(results, params), ...
        'residual_norm', results.iteration_log(results.iterations).residual_norm, ...
        'max_abs_gap', results.update_diagnostics.max_abs_gap, ...
        'price_min', min(results.final_price_path), ...
        'price_max', max(results.final_price_path), ...
        'policy_reference_min_used', min(policy_ref_path), ...
        'policy_reference_max_used', max(policy_ref_path), ...
        'floor_binding_periods', sum(floor_mask), ...
        'cap_binding_periods', sum(cap_mask), ...
        'elapsed_seconds', elapsed_seconds);

    for t = 1:T_full
        path_row_idx = path_row_idx + 1;
        path_rows(path_row_idx) = struct( ...
            'case_name', case_spec.case_name, ...
            'period_index', t, ...
            'calendar_year', calendar_years(t), ...
            'final_price', results.final_price_path(t), ...
            'implied_price', results.implied_price_path(t), ...
            'policy_reference_price_used', policy_ref_path(t), ...
            'floor_binding', floor_mask(t), ...
            'cap_binding', cap_mask(t), ...
            'Hdemand', results.Hdemand_path(t), ...
            'Hsupply', results.Hsupply_path(t), ...
            'excess_demand', results.excess_demand_path(t));
    end

    fprintf(['  gap=%.6f residual=%.6f range=[%.4f, %.4f] policy_ref=[%.4f, %.4f] ' ...
        'floor_bind=%d cap_bind=%d stable=%d\n'], ...
        summary_rows(i).max_abs_gap, summary_rows(i).residual_norm, ...
        summary_rows(i).price_min, summary_rows(i).price_max, ...
        summary_rows(i).policy_reference_min_used, summary_rows(i).policy_reference_max_used, ...
        summary_rows(i).floor_binding_periods, summary_rows(i).cap_binding_periods, ...
        summary_rows(i).looks_stable);
end

summary = struct2table(summary_rows);
path_table = struct2table(path_rows(1:path_row_idx));

writetable(summary, fullfile(this_dir, 'transition_re_policy_bridge_band_sweep_summary.csv'));
writetable(path_table, fullfile(this_dir, 'transition_re_policy_bridge_band_sweep_paths.csv'));
save(fullfile(this_dir, 'transition_re_policy_bridge_band_sweep_results.mat'), ...
    'summary', 'path_table', 'all_results', 'cases', 'common_guess', 'guess_source');
end

function params = default_band_sweep_params()
params = struct();
params.max_iter = 25;
params.tol = 1e-4;
params.damping = 0.25;
params.max_update_frac = 0.10;
params.smoothing_weight = 5.00;
params.terminal_anchor_weight = 0.50;
params.targeted_correction_weight = 0.35;
params.max_targeted_periods = 3;
params.target_block_half_width = 1;
params.line_search_scales = [0.01, 0.02, 0.05];
params.update_scheme = 'sequential_blocks';
params.outer_iteration_mode = 'fertility_style';
params.fixed_point_relaxation_weight = 0.10;
params.fixed_point_relaxation_space = 'log';
params.fixed_point_price_min = 0.40;
params.fixed_point_price_max = 5.00;
params.terminal_price_rule = 'flat_tail';
params.terminal_reference_mode = 'fixed_price';
params.terminal_reference_price = 2.0;
params.transition_policy_mode = 'steady_state_by_period_price';
params.policy_reference_mode = 'path_current_prices';
params.policy_reference_price = NaN;
params.policy_reference_price_floor = NaN;
params.policy_reference_price_cap = NaN;
end

function cases = build_band_cases()
cases = [ ...
    struct( ...
        'case_name', "steady_state_fixed_price_2_0_benchmark", ...
        'description', "Fixed-price policy bridge benchmark at price 2.0.", ...
        'transition_policy_mode', "steady_state_fixed_price", ...
        'policy_reference_mode', "fixed_price", ...
        'policy_reference_price', 2.0, ...
        'policy_reference_price_floor', NaN, ...
        'policy_reference_price_cap', NaN), ...
    struct( ...
        'case_name', "steady_state_by_period_price_band_1.95_2.05", ...
        'description', "By-period-price bridge clipped to [1.95, 2.05].", ...
        'transition_policy_mode', "steady_state_by_period_price", ...
        'policy_reference_mode', "path_current_prices", ...
        'policy_reference_price', NaN, ...
        'policy_reference_price_floor', 1.95, ...
        'policy_reference_price_cap', 2.05), ...
    struct( ...
        'case_name', "steady_state_by_period_price_band_1.95_2.10", ...
        'description', "By-period-price bridge clipped to [1.95, 2.10].", ...
        'transition_policy_mode', "steady_state_by_period_price", ...
        'policy_reference_mode', "path_current_prices", ...
        'policy_reference_price', NaN, ...
        'policy_reference_price_floor', 1.95, ...
        'policy_reference_price_cap', 2.10), ...
    struct( ...
        'case_name', "steady_state_by_period_price_band_1.90_2.10", ...
        'description', "By-period-price bridge clipped to [1.90, 2.10].", ...
        'transition_policy_mode', "steady_state_by_period_price", ...
        'policy_reference_mode', "path_current_prices", ...
        'policy_reference_price', NaN, ...
        'policy_reference_price_floor', 1.90, ...
        'policy_reference_price_cap', 2.10), ...
    struct( ...
        'case_name', "steady_state_by_period_price_band_1.90_2.15", ...
        'description', "By-period-price bridge clipped to [1.90, 2.15].", ...
        'transition_policy_mode', "steady_state_by_period_price", ...
        'policy_reference_mode', "path_current_prices", ...
        'policy_reference_price', NaN, ...
        'policy_reference_price_floor', 1.90, ...
        'policy_reference_price_cap', 2.15) ...
    ];
end

function [common_guess, guess_source] = load_common_guess(this_dir, T_full)
fixed_price_results_path = fullfile(this_dir, 'transition_re_k_step_policy_bridge_steady_state_fixed_price_2_0_results.mat');

if isfile(fixed_price_results_path)
    loaded = load(fixed_price_results_path, 'all_results');
    if isfield(loaded, 'all_results') && ~isempty(loaded.all_results) && ...
            numel(loaded.all_results) >= T_full && ~isempty(loaded.all_results{T_full})
        common_guess = loaded.all_results{T_full}.final_price_path(:);
        guess_source = "transition_re_k_step_policy_bridge_steady_state_fixed_price_2_0_results.final_price_path";
        return;
    end
end

common_guess = 2.0 .* ones(T_full, 1);
guess_source = "flat_2.0";
end

function tf = looks_stable(results, params)
tol = 1e-6;
tf = results.update_diagnostics.max_abs_gap < 0.05 && ...
    min(results.final_price_path) > params.fixed_point_price_min + tol && ...
    max(results.final_price_path) < params.fixed_point_price_max - tol;
end
