function [summary, periods, results_by_case] = run_transition_re_construction_adjustment_sweep(max_k, adjustment_weights)
% Compare the baseline instant-clearing path against a reduced-form
% construction-lag price-adjustment branch.

if nargin < 1 || isempty(max_k)
    max_k = 4;
end
if nargin < 2 || isempty(adjustment_weights)
    adjustment_weights = [1.00; 0.75; 0.50; 0.25];
end

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

demographic_path_full = build_demographic_path_from_age_state_csv(project_root);
T_full = numel(demographic_path_full.periods);
max_k = min(max(1, round(max_k)), T_full);
demographic_path = truncate_demographic_path_local(demographic_path_full, max_k);

price_path_guess = 2.0 .* ones(max_k, 1);
guess_source = "flat_2.0";
previous_results_path = fullfile(this_dir, 'transition_re_no_politics_results.mat');
if isfile(previous_results_path)
    loaded = load(previous_results_path, 'results');
    if isfield(loaded, 'results') && isfield(loaded.results, 'final_price_path') && ...
            numel(loaded.results.final_price_path) >= max_k
        price_path_guess = loaded.results.final_price_path(1:max_k);
        guess_source = "transition_re_no_politics_results.final_price_path_prefix";
    end
end

adjustment_weights = adjustment_weights(:);
case_n = numel(adjustment_weights);
summary_rows = cell(case_n, 1);
period_rows = cell(case_n, 1);
results_by_case = cell(case_n, 1);

fprintf('=== Construction-adjustment sweep ===\n');
fprintf('Periods: %d\n', max_k);
fprintf('Guess source: %s\n', guess_source);

for case_idx = 1:case_n
    weight = adjustment_weights(case_idx);
    params = default_params_local(weight);
    if abs(weight - 1.0) < 1e-12
        case_name = "instant_market_clearing";
    else
        case_name = string(sprintf('construction_lag_w%0.2f', weight));
    end

    fprintf('Running %s...\n', case_name);
    tic;
    results = solve_transition_re_no_politics(price_path_guess, demographic_path, params);
    elapsed_seconds = toc;
    iter_idx = results.iterations;

    max_abs_equal_weight_vote = NaN;
    max_abs_weighted_vote = NaN;
    if isfield(results, 'political')
        max_abs_equal_weight_vote = max(abs(results.political.equal_weight_vote_path));
        max_abs_weighted_vote = max(abs(results.political.weighted_vote_path));
    end

    summary_rows{case_idx} = table( ...
        case_name, ...
        max_k, ...
        string(guess_source), ...
        string(params.housing_adjustment_mode), ...
        params.housing_adjustment_weight, ...
        string(params.housing_adjustment_space), ...
        results.iterations, ...
        results.converged, ...
        results.iteration_log(iter_idx).residual_norm, ...
        results.update_diagnostics.max_abs_gap, ...
        results.iteration_log(iter_idx).max_abs_update, ...
        string(results.iteration_log(iter_idx).accepted_update), ...
        max_abs_equal_weight_vote, ...
        max_abs_weighted_vote, ...
        min(results.final_price_path), ...
        max(results.final_price_path), ...
        min(results.implied_price_path), ...
        max(results.implied_price_path), ...
        elapsed_seconds, ...
        'VariableNames', { ...
            'case_name', ...
            'horizon_k', ...
            'guess_source', ...
            'housing_adjustment_mode', ...
            'housing_adjustment_weight', ...
            'housing_adjustment_space', ...
            'iterations_completed', ...
            'converged', ...
            'residual_norm', ...
            'max_abs_gap', ...
            'max_abs_update', ...
            'accepted_update', ...
            'max_abs_equal_weight_vote', ...
            'max_abs_weighted_vote', ...
            'price_min', ...
            'price_max', ...
            'implied_price_min', ...
            'implied_price_max', ...
            'elapsed_seconds'});

    period_rows{case_idx} = table( ...
        repmat(case_name, max_k, 1), ...
        (1:max_k)', ...
        demographic_path.years(:), ...
        price_path_guess(:), ...
        results.final_price_path(:), ...
        results.period_diagnostics.instant_implied_price_path(:), ...
        results.implied_price_path(:), ...
        results.Hdemand_path(:), ...
        results.Hsupply_path(:), ...
        results.excess_demand_path(:), ...
        'VariableNames', { ...
            'case_name', ...
            'period_index', ...
            'year', ...
            'price_guess', ...
            'final_price', ...
            'instant_implied_price', ...
            'construction_adjusted_implied_price', ...
            'housing_demand', ...
            'housing_supply', ...
            'excess_demand'});

    if isfield(results, 'political')
        period_rows{case_idx}.equal_weight_vote = results.political.equal_weight_vote_path(:);
        period_rows{case_idx}.weighted_vote = results.political.weighted_vote_path(:);
    end

    results_by_case{case_idx} = results;
end

summary = vertcat(summary_rows{:});
periods = vertcat(period_rows{:});

writetable(summary, fullfile(this_dir, 'transition_re_construction_adjustment_sweep_summary.csv'));
writetable(periods, fullfile(this_dir, 'transition_re_construction_adjustment_sweep_periods.csv'));
save(fullfile(this_dir, 'transition_re_construction_adjustment_sweep_results.mat'), ...
    'summary', 'periods', 'results_by_case', 'demographic_path', 'price_path_guess', 'guess_source', 'adjustment_weights');
end

function params = default_params_local(adjustment_weight)
params = struct();
params.max_iter = 1;
params.tol = 1e-4;
params.damping = 0.25;
params.max_update_frac = 0.10;
params.smoothing_weight = 5.00;
params.terminal_anchor_weight = 0.50;
params.targeted_correction_weight = 0.35;
params.max_targeted_periods = 3;
params.target_block_half_width = 1;
params.line_search_scales = [0.01, 0.02, 0.05];
params.update_scheme = 'sequential_blocks';
params.transition_policy_mode = 'full_backward';
params.terminal_price_rule = 'flat_tail';
params.terminal_reference_mode = 'path_end_price';
params.compute_political_path = true;
params.save_political_details = false;
params.save_period_details = false;
params.coalition_params = struct();
params.housing_adjustment_weight = adjustment_weight;
params.housing_adjustment_space = 'log';
params.housing_adjustment_anchor_price = NaN;
if abs(adjustment_weight - 1.0) < 1e-12
    params.housing_adjustment_mode = 'instant_market_clearing';
else
    params.housing_adjustment_mode = 'construction_lag_price_partial_adjustment';
end
end

function demographic_path_k = truncate_demographic_path_local(demographic_path_full, k)
demographic_path_k = demographic_path_full;
fields = fieldnames(demographic_path_full);
for i = 1:numel(fields)
    field_name = fields{i};
    value = demographic_path_full.(field_name);
    if isnumeric(value)
        if isvector(value) && numel(value) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        elseif ismatrix(value) && size(value, 1) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        else
            demographic_path_k.(field_name) = value;
        end
    else
        demographic_path_k.(field_name) = value;
    end
end
demographic_path_k.description = sprintf('%s Truncated to first %d periods for the construction-adjustment sweep.', ...
    demographic_path_full.description, k);
end
