function summary = run_transition_re_policy_bridge_blend_sweep(blend_grid, output_tag)
% Sweep a convex blend between the fixed benchmark policy-reference path
% and the current-price path. alpha = 0 reproduces the fixed-price bridge;
% alpha = 1 reproduces the by-period-price bridge.

if nargin < 1 || isempty(blend_grid)
    blend_grid = [0.00, 0.05, 0.10, 0.20, 0.35, 0.50, 1.00];
end
if nargin < 2 || isempty(output_tag)
    output_tag = 'blend_sweep';
end

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

demographic_path_full = build_demographic_path_from_age_state_csv(project_root);
T_full = numel(demographic_path_full.periods);
calendar_years = demographic_path_full.periods(:);

[common_guess, guess_source] = load_common_guess(this_dir, T_full);
cases = build_blend_cases(blend_grid);
base_params = default_blend_sweep_params();

summary_rows = repmat(struct( ...
    'case_name', "", ...
    'description', "", ...
    'policy_reference_blend_weight', NaN, ...
    'status', "", ...
    'iterations_completed', NaN, ...
    'converged', false, ...
    'looks_stable', false, ...
    'residual_norm', NaN, ...
    'max_abs_gap', NaN, ...
    'max_abs_update', NaN, ...
    'price_min', NaN, ...
    'price_max', NaN, ...
    'path_span', NaN, ...
    'policy_reference_min_used', NaN, ...
    'policy_reference_max_used', NaN, ...
    'warm_start_source', "", ...
    'elapsed_seconds', NaN), numel(cases), 1);

path_rows = repmat(struct( ...
    'case_name', "", ...
    'blend_weight', NaN, ...
    'period_index', NaN, ...
    'calendar_year', NaN, ...
    'final_price', NaN, ...
    'implied_price', NaN, ...
    'policy_reference_price_used', NaN, ...
    'Hdemand', NaN, ...
    'Hsupply', NaN, ...
    'excess_demand', NaN, ...
    'rent_share', NaN), numel(cases) * T_full, 1);
path_row_idx = 0;

all_results = cell(numel(cases), 1);
current_guess = common_guess;

fprintf('=== NIMBY RE policy-bridge blend sweep ===\n');
fprintf('Warm start source: %s\n', guess_source);
fprintf('Continuation ladder over alpha values: %s\n', mat2str(blend_grid));

for i = 1:numel(cases)
    case_spec = cases(i);
    params = base_params;
    params.policy_reference_blend_weight = case_spec.policy_reference_blend_weight;

    fprintf('\nRunning case %s ...\n', case_spec.case_name);
    case_tic = tic;
    results = solve_transition_re_no_politics(current_guess, demographic_path_full, params);
    elapsed_seconds = toc(case_tic);
    all_results{i} = results;

    iter_idx = results.iterations;
    policy_ref_path = results.policy_reference_price_path_used(:);

    summary_rows(i) = struct( ...
        'case_name', case_spec.case_name, ...
        'description', case_spec.description, ...
        'policy_reference_blend_weight', case_spec.policy_reference_blend_weight, ...
        'status', "ok", ...
        'iterations_completed', iter_idx, ...
        'converged', results.converged, ...
        'looks_stable', looks_stable(results, params), ...
        'residual_norm', results.iteration_log(iter_idx).residual_norm, ...
        'max_abs_gap', results.update_diagnostics.max_abs_gap, ...
        'max_abs_update', results.iteration_log(iter_idx).max_abs_update, ...
        'price_min', min(results.final_price_path), ...
        'price_max', max(results.final_price_path), ...
        'path_span', max(results.final_price_path) - min(results.final_price_path), ...
        'policy_reference_min_used', min(policy_ref_path), ...
        'policy_reference_max_used', max(policy_ref_path), ...
        'warm_start_source', guess_source, ...
        'elapsed_seconds', elapsed_seconds);

    for t = 1:T_full
        path_row_idx = path_row_idx + 1;
        path_rows(path_row_idx) = struct( ...
            'case_name', case_spec.case_name, ...
            'blend_weight', case_spec.policy_reference_blend_weight, ...
            'period_index', t, ...
            'calendar_year', calendar_years(t), ...
            'final_price', results.final_price_path(t), ...
            'implied_price', results.implied_price_path(t), ...
            'policy_reference_price_used', policy_ref_path(t), ...
            'Hdemand', results.Hdemand_path(t), ...
            'Hsupply', results.Hsupply_path(t), ...
            'excess_demand', results.excess_demand_path(t), ...
            'rent_share', results.rent_share_path(t));
    end

    fprintf('  alpha=%.2f gap=%.6f residual=%.6f range=[%.4f, %.4f] stable=%d\n', ...
        case_spec.policy_reference_blend_weight, summary_rows(i).max_abs_gap, ...
        summary_rows(i).residual_norm, summary_rows(i).price_min, summary_rows(i).price_max, ...
        summary_rows(i).looks_stable);

    current_guess = results.final_price_path(:);
    guess_source = sprintf('alpha_%.2f_final_price_path', case_spec.policy_reference_blend_weight);

    summary_partial = struct2table(summary_rows(1:i));
    path_table_partial = struct2table(path_rows(1:path_row_idx));
    writetable(summary_partial, fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_summary.csv', output_tag)));
    writetable(path_table_partial, fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_paths.csv', output_tag)));
    save(fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_results.mat', output_tag)), ...
        'summary_partial', 'path_table_partial', 'all_results', 'cases', 'common_guess', 'guess_source');
end

summary = struct2table(summary_rows);
path_table = struct2table(path_rows(1:path_row_idx));

writetable(summary, fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_summary.csv', output_tag)));
writetable(path_table, fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_paths.csv', output_tag)));
save(fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_results.mat', output_tag)), ...
    'summary', 'path_table', 'all_results', 'cases', 'common_guess', 'guess_source');
end

function params = default_blend_sweep_params()
params = struct();
params.max_iter = 15;
params.tol = 1e-4;
params.damping = 0.25;
params.max_update_frac = 0.10;
params.smoothing_weight = 5.00;
params.terminal_anchor_weight = 0.50;
params.targeted_correction_weight = 0.35;
params.max_targeted_periods = 3;
params.target_block_half_width = 1;
params.line_search_scales = [0.01, 0.02, 0.05];
params.update_scheme = 'sequential_blocks';
params.outer_iteration_mode = 'fertility_style';
params.fixed_point_relaxation_weight = 0.10;
params.fixed_point_relaxation_space = 'log';
params.fixed_point_price_min = 0.40;
params.fixed_point_price_max = 5.00;
params.terminal_price_rule = 'flat_tail';
params.terminal_reference_mode = 'fixed_price';
params.terminal_reference_price = 2.0;
params.transition_policy_mode = 'steady_state_by_period_price';
params.policy_reference_mode = 'blended_current_and_fixed_price';
params.policy_reference_price = 2.0;
params.policy_reference_blend_weight = 0.0;
params.policy_reference_price_floor = NaN;
params.policy_reference_price_cap = NaN;
end

function cases = build_blend_cases(blend_grid)
cases = repmat(struct( ...
    'case_name', "", ...
    'description', "", ...
    'policy_reference_blend_weight', NaN), numel(blend_grid), 1);

for i = 1:numel(blend_grid)
    alpha = blend_grid(i);
    alpha_label = format_blend_label(alpha);
    cases(i) = struct( ...
        'case_name', string(sprintf('steady_state_blend_alpha_%s', alpha_label)), ...
        'description', string(sprintf('Policy-reference blend with alpha = %.2f between fixed 2.0 and current prices.', alpha)), ...
        'policy_reference_blend_weight', alpha);
end
end

function label = format_blend_label(alpha)
label = regexprep(sprintf('%.3f', alpha), '0+$', '');
label = regexprep(label, '\.$', '');
label = strrep(label, '.', '_');
end

function [common_guess, guess_source] = load_common_guess(this_dir, T_full)
fixed_price_results_path = fullfile(this_dir, 'transition_re_k_step_policy_bridge_steady_state_fixed_price_2_0_results.mat');

if isfile(fixed_price_results_path)
    loaded = load(fixed_price_results_path, 'all_results');
    if isfield(loaded, 'all_results') && ~isempty(loaded.all_results) && ...
            numel(loaded.all_results) >= T_full && ~isempty(loaded.all_results{T_full})
        common_guess = loaded.all_results{T_full}.final_price_path(:);
        guess_source = "transition_re_k_step_policy_bridge_steady_state_fixed_price_2_0_results.final_price_path";
        return;
    end
end

common_guess = 2.0 .* ones(T_full, 1);
guess_source = "flat_2.0";
end

function tf = looks_stable(results, params)
tol = 1e-6;
tf = results.update_diagnostics.max_abs_gap < 0.05 && ...
    min(results.final_price_path) > params.fixed_point_price_min + tol && ...
    max(results.final_price_path) < params.fixed_point_price_max - tol;
end
