function summary = run_transition_re_reduced_form_one_step(re_weight_grid)
% Run the first bounded reduced-form RE pass on the NIMBY demographic path.
% This solves only the next-period price with a flat benchmark tail after
% t = 1, mirroring the first fertility reduced-form rung.

if nargin < 1 || isempty(re_weight_grid)
    re_weight_grid = 1.00;
end

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

operator = build_reduced_form_price_operator_from_policy_bridge(project_root);
base_params = default_one_step_params(operator);

summary_rows = repmat(struct( ...
    're_weight', NaN, ...
    'status', "", ...
    'iterations_completed', NaN, ...
    'converged', false, ...
    'looks_stable', false, ...
    'solved_price_t1', NaN, ...
    'implied_price_t1', NaN, ...
    'price_gap_t1', NaN, ...
    'solved_year_t1', NaN, ...
    'young_share_25_44_t1', NaN, ...
    'pressure_index_t1', NaN, ...
    'tail_price', NaN, ...
    'price_min', NaN, ...
    'price_max', NaN, ...
    'elapsed_seconds', NaN), numel(re_weight_grid), 1);

all_results = cell(numel(re_weight_grid), 1);

fprintf('=== NIMBY reduced-form one-step RE ===\n');
fprintf('Operator source: %s\n', operator.benchmark_source);
fprintf('Raw next-price coeff = %.4f, bounded coeff = %.4f, bounded-fit RMSE = %.6f\n', ...
    operator.raw_next_price_coeff, operator.next_price_coeff, operator.bounded_fit_rmse);

for i = 1:numel(re_weight_grid)
    params = base_params;
    params.re_weight = re_weight_grid(i);

    case_tic = tic;
    results = solve_reduced_form_price_path(operator, 1, params, params.tail_price);
    elapsed_seconds = toc(case_tic);
    all_results{i} = results;

    summary_rows(i) = struct( ...
        're_weight', params.re_weight, ...
        'status', results.status, ...
        'iterations_completed', results.iterations_completed, ...
        'converged', results.converged, ...
        'looks_stable', results.looks_stable, ...
        'solved_price_t1', results.final_price_path(1), ...
        'implied_price_t1', results.implied_price_path(1), ...
        'price_gap_t1', results.implied_price_path(1) - results.final_price_path(1), ...
        'solved_year_t1', results.years(1), ...
        'young_share_25_44_t1', results.young_share_25_44(1), ...
        'pressure_index_t1', results.pressure_index(1), ...
        'tail_price', params.tail_price, ...
        'price_min', params.price_min, ...
        'price_max', params.price_max, ...
        'elapsed_seconds', elapsed_seconds);

    fprintf('  weight %.2f: p1=%.6f, implied=%.6f, gap=%.6e, stable=%d\n', ...
        params.re_weight, summary_rows(i).solved_price_t1, summary_rows(i).implied_price_t1, ...
        summary_rows(i).price_gap_t1, summary_rows(i).looks_stable);
end

summary = struct2table(summary_rows);
writetable(summary, fullfile(this_dir, 'transition_re_reduced_form_one_step_summary.csv'));
save(fullfile(this_dir, 'transition_re_reduced_form_one_step_results.mat'), ...
    'summary', 'all_results', 'operator', 're_weight_grid');
end

function params = default_one_step_params(operator)
params = struct();
params.max_iter = 100;
params.tol = 1e-8;
params.relaxation_weight = 0.50;
params.re_weight = 1.0;
params.price_min = 1.75;
params.price_max = 2.25;
params.tail_price = operator.tail_price;
params.start_index = 2;
end
