function [summary, paths] = run_transition_re_policy_bridge_k4_warm_start_diagnostics(output_tag)
% Diagnose whether the alpha = 0.14, k = 4 instability is a warm-start / basin issue.

if nargin < 1 || isempty(output_tag)
    output_tag = 'k4_warm_start_diagnostics';
end

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

demographic_path_full = build_demographic_path_from_age_state_csv(project_root);
demographic_path_k4 = truncate_demographic_path(demographic_path_full, 4);

results_014 = load(fullfile(this_dir, 'transition_re_policy_bridge_alpha_frontier_single_0_14_k6_results.mat'), 'state');
results_013 = load(fullfile(this_dir, 'transition_re_policy_bridge_alpha_frontier_single_0_13_k6_results.mat'), 'state');

state_014 = results_014.state;
state_013 = results_013.state;

anchor_price_path = state_014.anchor_price_path(:);
anchor_source = string(state_014.anchor_source);

alpha = 0.14;
cases = build_case_specs(state_014, state_013, anchor_price_path);

summary_rows = repmat(struct( ...
    'case_name', "", ...
    'guess_source', "", ...
    'alpha', NaN, ...
    'k', NaN, ...
    'max_iter', NaN, ...
    'status', "", ...
    'iterations_completed', NaN, ...
    'converged', false, ...
    'looks_stable', false, ...
    'residual_norm', NaN, ...
    'max_abs_gap', NaN, ...
    'max_abs_update', NaN, ...
    'accepted_update', "", ...
    'worst_gap_period', NaN, ...
    'worst_excess_demand_period', NaN, ...
    'worst_excess_demand', NaN, ...
    'price_min', NaN, ...
    'price_max', NaN, ...
    'path_span', NaN, ...
    'policy_reference_price_first_used', NaN, ...
    'policy_reference_price_last_used', NaN, ...
    'elapsed_seconds', NaN, ...
    'start_price_1', NaN, ...
    'start_price_2', NaN, ...
    'start_price_3', NaN, ...
    'start_price_4', NaN, ...
    'final_price_1', NaN, ...
    'final_price_2', NaN, ...
    'final_price_3', NaN, ...
    'final_price_4', NaN, ...
    'implied_price_1', NaN, ...
    'implied_price_2', NaN, ...
    'implied_price_3', NaN, ...
    'implied_price_4', NaN), numel(cases), 1);

path_rows = repmat(struct( ...
    'case_name', "", ...
    'guess_source', "", ...
    'alpha', NaN, ...
    'k', NaN, ...
    'max_iter', NaN, ...
    'period', NaN, ...
    'start_price', NaN, ...
    'final_price', NaN, ...
    'implied_price', NaN, ...
    'policy_reference_price_used', NaN, ...
    'Hdemand', NaN, ...
    'Hsupply', NaN, ...
    'excess_demand', NaN), numel(cases) * 4, 1);
path_idx = 0;

all_results = cell(numel(cases), 1);
paths_struct = build_output_paths(this_dir, output_tag);

fprintf('=== NIMBY RE policy-bridge k=4 warm-start diagnostics ===\n');
fprintf('Anchor source: %s\n', anchor_source);
fprintf('Target alpha: %.5f\n', alpha);
fprintf('Target horizon: k = 4\n');

for i = 1:numel(cases)
    case_spec = cases(i);
    params = default_diag_params(alpha, case_spec.max_iter);

    fprintf('\nRunning case %s ...\n', case_spec.case_name);
    fprintf('  guess source: %s\n', case_spec.guess_source);
    fprintf('  start path: %s\n', mat2str(case_spec.guess(:)', 6));

    run_tic = tic;
    try
        results = solve_transition_re_no_politics(case_spec.guess, demographic_path_k4, params);
        elapsed_seconds = toc(run_tic);
        all_results{i} = results;

        iter_idx = results.iterations;
        policy_ref_path = results.policy_reference_price_path_used(:);
        summary_rows(i) = build_summary_row(case_spec, alpha, 4, results, elapsed_seconds, policy_ref_path);

        [path_rows, path_idx] = append_path_rows(path_rows, path_idx, case_spec, alpha, 4, results);

        fprintf('  gap=%.6f residual=%.6f range=[%.4f, %.4f] stable=%d\n', ...
            summary_rows(i).max_abs_gap, ...
            summary_rows(i).residual_norm, ...
            summary_rows(i).price_min, ...
            summary_rows(i).price_max, ...
            summary_rows(i).looks_stable);
    catch ME
        elapsed_seconds = toc(run_tic);
        summary_rows(i) = build_error_row(case_spec, alpha, 4, elapsed_seconds);
        save_partial_outputs(paths_struct, summary_rows(1:i), path_rows(1:path_idx), all_results, cases, anchor_source, ME);
        rethrow(ME);
    end

    save_partial_outputs(paths_struct, summary_rows(1:i), path_rows(1:path_idx), all_results, cases, anchor_source);
end

summary = struct2table(summary_rows);
paths = struct2table(path_rows(1:path_idx));

writetable(summary, paths_struct.summary_path);
writetable(paths, paths_struct.paths_path);
save(paths_struct.results_path, 'summary', 'paths', 'all_results', 'cases', 'anchor_source');
end

function cases = build_case_specs(state_014, state_013, anchor_price_path)
guess_k3 = extend_guess(state_014.all_results{3, 1}.final_price_path(:), anchor_price_path, 4);
guess_restart_k4 = state_014.all_results{4, 1}.final_price_path(:);
guess_a013_k4 = state_013.all_results{4, 1}.final_price_path(:);
guess_a014_k5_prefix = state_014.all_results{5, 1}.final_price_path(1:4);
guess_a014_k6_prefix = state_014.all_results{6, 1}.final_price_path(1:4);

cases = [ ...
    struct( ...
        'case_name', "default_same_alpha_k3_iter25", ...
        'guess_source', "alpha_0_14_k3_extended_with_anchor_period_4", ...
        'guess', guess_k3, ...
        'max_iter', 25), ...
    struct( ...
        'case_name', "default_same_alpha_k3_iter50", ...
        'guess_source', "alpha_0_14_k3_extended_with_anchor_period_4", ...
        'guess', guess_k3, ...
        'max_iter', 50), ...
    struct( ...
        'case_name', "restart_from_failed_alpha_0_14_k4", ...
        'guess_source', "alpha_0_14_k4_final_price_path", ...
        'guess', guess_restart_k4, ...
        'max_iter', 25), ...
    struct( ...
        'case_name', "restart_from_stable_alpha_0_13_k4", ...
        'guess_source', "alpha_0_13_k4_final_price_path", ...
        'guess', guess_a013_k4, ...
        'max_iter', 25), ...
    struct( ...
        'case_name', "restart_from_alpha_0_14_k5_prefix", ...
        'guess_source', "alpha_0_14_k5_final_price_path_prefix", ...
        'guess', guess_a014_k5_prefix, ...
        'max_iter', 25), ...
    struct( ...
        'case_name', "restart_from_alpha_0_14_k6_prefix", ...
        'guess_source', "alpha_0_14_k6_final_price_path_prefix", ...
        'guess', guess_a014_k6_prefix, ...
        'max_iter', 25) ...
    ];
end

function params = default_diag_params(alpha, max_iter)
params = struct();
params.max_iter = max_iter;
params.tol = 1e-4;
params.damping = 0.25;
params.max_update_frac = 0.10;
params.smoothing_weight = 5.00;
params.terminal_anchor_weight = 0.50;
params.targeted_correction_weight = 0.35;
params.max_targeted_periods = 3;
params.target_block_half_width = 1;
params.line_search_scales = [0.01, 0.02, 0.05];
params.update_scheme = 'sequential_blocks';
params.outer_iteration_mode = 'fertility_style';
params.fixed_point_relaxation_weight = 0.10;
params.fixed_point_relaxation_space = 'log';
params.fixed_point_price_min = 0.40;
params.fixed_point_price_max = 5.00;
params.terminal_price_rule = 'flat_tail';
params.terminal_reference_mode = 'fixed_price';
params.terminal_reference_price = 2.0;
params.transition_policy_mode = 'steady_state_by_period_price';
params.policy_reference_mode = 'blended_current_and_fixed_price';
params.policy_reference_price = 2.0;
params.policy_reference_blend_weight = alpha;
params.policy_reference_price_floor = NaN;
params.policy_reference_price_cap = NaN;
end

function summary_row = build_summary_row(case_spec, alpha, k, results, elapsed_seconds, policy_ref_path)
iter_idx = results.iterations;
final_path = results.final_price_path(:);
implied_path = results.implied_price_path(:);
start_path = case_spec.guess(:);

summary_row = struct( ...
    'case_name', case_spec.case_name, ...
    'guess_source', case_spec.guess_source, ...
    'alpha', alpha, ...
    'k', k, ...
    'max_iter', case_spec.max_iter, ...
    'status', "ok", ...
    'iterations_completed', iter_idx, ...
    'converged', results.converged, ...
    'looks_stable', looks_stable(results, results.params), ...
    'residual_norm', results.iteration_log(iter_idx).residual_norm, ...
    'max_abs_gap', results.update_diagnostics.max_abs_gap, ...
    'max_abs_update', results.iteration_log(iter_idx).max_abs_update, ...
    'accepted_update', string(results.iteration_log(iter_idx).accepted_update), ...
    'worst_gap_period', results.iteration_log(iter_idx).worst_gap_period, ...
    'worst_excess_demand_period', results.iteration_log(iter_idx).worst_excess_demand_period, ...
    'worst_excess_demand', results.iteration_log(iter_idx).worst_excess_demand, ...
    'price_min', min(final_path), ...
    'price_max', max(final_path), ...
    'path_span', max(final_path) - min(final_path), ...
    'policy_reference_price_first_used', policy_ref_path(1), ...
    'policy_reference_price_last_used', policy_ref_path(end), ...
    'elapsed_seconds', elapsed_seconds, ...
    'start_price_1', start_path(1), ...
    'start_price_2', start_path(2), ...
    'start_price_3', start_path(3), ...
    'start_price_4', start_path(4), ...
    'final_price_1', final_path(1), ...
    'final_price_2', final_path(2), ...
    'final_price_3', final_path(3), ...
    'final_price_4', final_path(4), ...
    'implied_price_1', implied_path(1), ...
    'implied_price_2', implied_path(2), ...
    'implied_price_3', implied_path(3), ...
    'implied_price_4', implied_path(4));
end

function summary_row = build_error_row(case_spec, alpha, k, elapsed_seconds)
summary_row = struct( ...
    'case_name', case_spec.case_name, ...
    'guess_source', case_spec.guess_source, ...
    'alpha', alpha, ...
    'k', k, ...
    'max_iter', case_spec.max_iter, ...
    'status', "error", ...
    'iterations_completed', NaN, ...
    'converged', false, ...
    'looks_stable', false, ...
    'residual_norm', NaN, ...
    'max_abs_gap', NaN, ...
    'max_abs_update', NaN, ...
    'accepted_update', "", ...
    'worst_gap_period', NaN, ...
    'worst_excess_demand_period', NaN, ...
    'worst_excess_demand', NaN, ...
    'price_min', NaN, ...
    'price_max', NaN, ...
    'path_span', NaN, ...
    'policy_reference_price_first_used', NaN, ...
    'policy_reference_price_last_used', NaN, ...
    'elapsed_seconds', elapsed_seconds, ...
    'start_price_1', case_spec.guess(1), ...
    'start_price_2', case_spec.guess(2), ...
    'start_price_3', case_spec.guess(3), ...
    'start_price_4', case_spec.guess(4), ...
    'final_price_1', NaN, ...
    'final_price_2', NaN, ...
    'final_price_3', NaN, ...
    'final_price_4', NaN, ...
    'implied_price_1', NaN, ...
    'implied_price_2', NaN, ...
    'implied_price_3', NaN, ...
    'implied_price_4', NaN);
end

function [path_rows, path_idx] = append_path_rows(path_rows, path_idx, case_spec, alpha, k, results)
start_path = case_spec.guess(:);
final_path = results.final_price_path(:);
implied_path = results.implied_price_path(:);
policy_ref_path = results.policy_reference_price_path_used(:);
Hdemand_path = results.Hdemand_path(:);
Hsupply_path = results.Hsupply_path(:);
excess_path = results.excess_demand_path(:);

for period = 1:k
    path_idx = path_idx + 1;
    path_rows(path_idx) = struct( ...
        'case_name', case_spec.case_name, ...
        'guess_source', case_spec.guess_source, ...
        'alpha', alpha, ...
        'k', k, ...
        'max_iter', case_spec.max_iter, ...
        'period', period, ...
        'start_price', start_path(period), ...
        'final_price', final_path(period), ...
        'implied_price', implied_path(period), ...
        'policy_reference_price_used', policy_ref_path(period), ...
        'Hdemand', Hdemand_path(period), ...
        'Hsupply', Hsupply_path(period), ...
        'excess_demand', excess_path(period));
    end
end

function paths_struct = build_output_paths(this_dir, output_tag)
paths_struct = struct();
paths_struct.summary_path = fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_summary.csv', output_tag));
paths_struct.paths_path = fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_paths.csv', output_tag));
paths_struct.results_path = fullfile(this_dir, sprintf('transition_re_policy_bridge_%s_results.mat', output_tag));
end

function save_partial_outputs(paths_struct, summary_rows, path_rows, all_results, cases, anchor_source, varargin)
summary_table = struct2table(summary_rows);
paths_table = struct2table(path_rows);

writetable(summary_table, paths_struct.summary_path);
writetable(paths_table, paths_struct.paths_path);

save_args = {'summary_table', 'paths_table', 'all_results', 'cases', 'anchor_source'};
if ~isempty(varargin)
    ME = varargin{1}; %#ok<NASGU>
    save_args = [save_args, {'ME'}];
end
save(paths_struct.results_path, save_args{:});
end

function tf = looks_stable(results, params)
tol = 1e-6;
tf = results.update_diagnostics.max_abs_gap < 0.05 && ...
    min(results.final_price_path) > params.fixed_point_price_min + tol && ...
    max(results.final_price_path) < params.fixed_point_price_max - tol;
end

function guess = extend_guess(current_guess, anchor_price_path, k)
guess = current_guess(:);
if numel(guess) >= k
    guess = guess(1:k);
else
    guess = [guess; anchor_price_path(numel(guess) + 1:k)];
end
end

function demographic_path_k = truncate_demographic_path(demographic_path_full, k)
demographic_path_k = demographic_path_full;
fields = fieldnames(demographic_path_full);
for i = 1:numel(fields)
    field_name = fields{i};
    value = demographic_path_full.(field_name);
    if isnumeric(value)
        if isvector(value) && numel(value) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        elseif ismatrix(value) && size(value, 1) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        else
            demographic_path_k.(field_name) = value;
        end
    else
        demographic_path_k.(field_name) = value;
    end
end
demographic_path_k.description = sprintf('%s Truncated to first %d periods for the k=4 warm-start diagnostics.', ...
    demographic_path_full.description, k);
end
