function [summary, frontier] = run_transition_re_reduced_form_k_step_ladder(horizon_grid, re_weight_grid)
% Sweep finite-horizon reduced-form RE ladders over horizons and RE weights.

if nargin < 1 || isempty(horizon_grid)
    horizon_grid = [1, 2, 3, 5, 8];
end
if nargin < 2 || isempty(re_weight_grid)
    re_weight_grid = [0.25, 0.50, 0.75, 1.00, 1.25];
end

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

operator = build_reduced_form_price_operator_from_policy_bridge(project_root);
base_params = default_k_step_params(operator);

T_full = numel(operator.periods);
max_horizon = T_full - base_params.start_index + 1;
horizon_grid = unique(max(1, min(max_horizon, round(horizon_grid(:)'))), 'stable');

max_rows = numel(horizon_grid) * numel(re_weight_grid);
summary_rows = repmat(struct( ...
    're_weight', NaN, ...
    'k', NaN, ...
    'status', "", ...
    'iterations_completed', NaN, ...
    'converged', false, ...
    'looks_stable', false, ...
    'max_abs_gap', NaN, ...
    'max_abs_log_gap', NaN, ...
    'price_1', NaN, ...
    'price_k', NaN, ...
    'price_min', NaN, ...
    'price_max', NaN, ...
    'path_span', NaN, ...
    'tail_price', NaN, ...
    'elapsed_seconds', NaN), max_rows, 1);

path_rows = repmat(struct( ...
    're_weight', NaN, ...
    'k', NaN, ...
    'period_index', NaN, ...
    'calendar_year', NaN, ...
    'final_price', NaN, ...
    'implied_price', NaN, ...
    'young_share_25_44', NaN, ...
    'pressure_index', NaN), max_rows * T_full, 1);

all_results = cell(numel(re_weight_grid), numel(horizon_grid));
summary_idx = 0;
path_idx = 0;

fprintf('=== NIMBY reduced-form k-step RE ladder ===\n');
fprintf('Operator source: %s\n', operator.benchmark_source);
fprintf('Raw next-price coeff = %.4f, bounded coeff = %.4f, bounded-fit RMSE = %.6f\n', ...
    operator.raw_next_price_coeff, operator.next_price_coeff, operator.bounded_fit_rmse);

for iw = 1:numel(re_weight_grid)
    params = base_params;
    params.re_weight = re_weight_grid(iw);
    current_guess = [];

    fprintf('\nWeight %.2f\n', params.re_weight);

    for ik = 1:numel(horizon_grid)
        k = horizon_grid(ik);
        case_tic = tic;
        results = solve_reduced_form_price_path(operator, k, params, current_guess);
        elapsed_seconds = toc(case_tic);
        all_results{iw, ik} = results;
        current_guess = results.final_price_path(:);

        summary_idx = summary_idx + 1;
        summary_rows(summary_idx) = struct( ...
            're_weight', params.re_weight, ...
            'k', k, ...
            'status', results.status, ...
            'iterations_completed', results.iterations_completed, ...
            'converged', results.converged, ...
            'looks_stable', results.looks_stable, ...
            'max_abs_gap', results.max_abs_gap, ...
            'max_abs_log_gap', results.max_abs_log_gap, ...
            'price_1', results.final_price_path(1), ...
            'price_k', results.final_price_path(end), ...
            'price_min', min(results.final_price_path), ...
            'price_max', max(results.final_price_path), ...
            'path_span', results.path_span, ...
            'tail_price', results.tail_price, ...
            'elapsed_seconds', elapsed_seconds);

        for t = 1:k
            path_idx = path_idx + 1;
            path_rows(path_idx) = struct( ...
                're_weight', params.re_weight, ...
                'k', k, ...
                'period_index', t, ...
                'calendar_year', results.years(t), ...
                'final_price', results.final_price_path(t), ...
                'implied_price', results.implied_price_path(t), ...
                'young_share_25_44', results.young_share_25_44(t), ...
                'pressure_index', results.pressure_index(t));
        end

        fprintf('  k=%d: p1=%.6f pk=%.6f gap=%.6e stable=%d\n', ...
            k, results.final_price_path(1), results.final_price_path(end), ...
            results.max_abs_gap, results.looks_stable);

        if ~results.looks_stable
            fprintf('  stopping weight %.2f after k=%d because the reduced-form ladder left the stable box.\n', ...
                params.re_weight, k);
            break;
        end
    end
end

summary = struct2table(summary_rows(1:summary_idx));
path_table = struct2table(path_rows(1:path_idx));
frontier = build_stability_frontier(summary, horizon_grid, re_weight_grid);

writetable(summary, fullfile(this_dir, 'transition_re_reduced_form_k_step_summary.csv'));
writetable(path_table, fullfile(this_dir, 'transition_re_reduced_form_k_step_paths.csv'));
writetable(frontier, fullfile(this_dir, 'transition_re_reduced_form_k_step_frontier.csv'));
save(fullfile(this_dir, 'transition_re_reduced_form_k_step_results.mat'), ...
    'summary', 'path_table', 'frontier', 'all_results', 'operator', 'horizon_grid', 're_weight_grid');
end

function params = default_k_step_params(operator)
params = struct();
params.max_iter = 100;
params.tol = 1e-8;
params.relaxation_weight = 0.50;
params.re_weight = 1.0;
params.price_min = 1.75;
params.price_max = 2.25;
params.tail_price = operator.tail_price;
params.start_index = 2;
end

function frontier = build_stability_frontier(summary, horizon_grid, re_weight_grid)
frontier_rows = repmat(struct( ...
    're_weight', NaN, ...
    'max_stable_horizon', NaN, ...
    'first_nonconverged_horizon', NaN), numel(re_weight_grid), 1);

for i = 1:numel(re_weight_grid)
    re_weight = re_weight_grid(i);
    rows = summary(summary.re_weight == re_weight, :);
    stable_rows = rows(rows.looks_stable, :);

    max_stable_horizon = 0;
    if ~isempty(stable_rows)
        max_stable_horizon = max(stable_rows.k);
    end

    first_nonconverged_horizon = NaN;
    for k = horizon_grid
        this_row = rows(rows.k == k, :);
        if isempty(this_row)
            first_nonconverged_horizon = k;
            break;
        end
        if ~this_row.looks_stable(1)
            first_nonconverged_horizon = k;
            break;
        end
    end

    frontier_rows(i) = struct( ...
        're_weight', re_weight, ...
        'max_stable_horizon', max_stable_horizon, ...
        'first_nonconverged_horizon', first_nonconverged_horizon);
end

frontier = struct2table(frontier_rows);
end
