function [summary, periods, results] = run_transition_re_political_path_diagnostic(max_k)
% Build a bounded transition-path political packet on top of the shared
% Bellman and political-path layers.

if nargin < 1 || isempty(max_k)
    max_k = 4;
end

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

demographic_path_full = build_demographic_path_from_age_state_csv(project_root);
T_full = numel(demographic_path_full.periods);
max_k = min(max(1, round(max_k)), T_full);
demographic_path = truncate_demographic_path_local(demographic_path_full, max_k);

price_path_guess = 2.0 .* ones(max_k, 1);
guess_source = "flat_2.0";
previous_results_path = fullfile(this_dir, 'transition_re_no_politics_results.mat');
if isfile(previous_results_path)
    loaded = load(previous_results_path, 'results');
    if isfield(loaded, 'results') && isfield(loaded.results, 'final_price_path') && ...
            numel(loaded.results.final_price_path) >= max_k
        price_path_guess = loaded.results.final_price_path(1:max_k);
        guess_source = "transition_re_no_politics_results.final_price_path_prefix";
    end
end

params = default_political_path_params_local();

fprintf('=== Bounded transition political-path diagnostic ===\n');
fprintf('Periods: %d\n', max_k);
fprintf('Price-guess source: %s\n', guess_source);

tic;
results = solve_transition_re_no_politics(price_path_guess, demographic_path, params);
elapsed_seconds = toc;

iter_idx = results.iterations;
political = results.political;

summary = table( ...
    string(sprintf('political_path_t%d', max_k)), ...
    max_k, ...
    string(guess_source), ...
    results.iterations, ...
    results.converged, ...
    results.iteration_log(iter_idx).residual_norm, ...
    results.update_diagnostics.max_abs_gap, ...
    results.iteration_log(iter_idx).max_abs_update, ...
    string(results.iteration_log(iter_idx).accepted_update), ...
    results.iteration_log(iter_idx).worst_gap_period, ...
    results.iteration_log(iter_idx).worst_excess_demand_period, ...
    results.iteration_log(iter_idx).worst_excess_demand, ...
    max(abs(political.equal_weight_vote_path)), ...
    max(abs(political.weighted_vote_path)), ...
    argmax_abs_local(political.equal_weight_vote_path), ...
    argmax_abs_local(political.weighted_vote_path), ...
    min(results.final_price_path), ...
    max(results.final_price_path), ...
    elapsed_seconds, ...
    'VariableNames', { ...
        'case_name', ...
        'horizon_k', ...
        'guess_source', ...
        'iterations_completed', ...
        'converged', ...
        'residual_norm', ...
        'max_abs_gap', ...
        'max_abs_update', ...
        'accepted_update', ...
        'worst_gap_period', ...
        'worst_excess_demand_period', ...
        'worst_excess_demand', ...
        'max_abs_equal_weight_vote', ...
        'max_abs_weighted_vote', ...
        'worst_equal_weight_vote_period', ...
        'worst_weighted_vote_period', ...
        'price_min', ...
        'price_max', ...
        'elapsed_seconds'});

period_index = (1:max_k)';
periods = table( ...
    period_index, ...
    demographic_path.years(:), ...
    price_path_guess(:), ...
    results.final_price_path(:), ...
    results.implied_price_path(:), ...
    results.Hdemand_path(:), ...
    results.Hsupply_path(:), ...
    results.excess_demand_path(:), ...
    political.equal_weight_vote_path(:), ...
    political.weighted_vote_path(:), ...
    political.weighted_vote_share_path(:), ...
    political.equal_weight_distance_path(:), ...
    political.weighted_distance_path(:), ...
    political.owner_share_path(:), ...
    political.old_owner_share_path(:), ...
    political.leveraged_owner_share_path(:), ...
    results.rent_share_path(:), ...
    'VariableNames', { ...
        'period_index', ...
        'year', ...
        'price_guess', ...
        'final_price', ...
        'implied_price', ...
        'housing_demand', ...
        'housing_supply', ...
        'excess_demand', ...
        'equal_weight_vote', ...
        'weighted_vote', ...
        'weighted_vote_share', ...
        'equal_weight_distance', ...
        'weighted_distance', ...
        'owner_share', ...
        'old_owner_share', ...
        'leveraged_owner_share', ...
        'rent_share'});

writetable(summary, fullfile(this_dir, 'transition_re_political_path_summary.csv'));
writetable(periods, fullfile(this_dir, 'transition_re_political_path_periods.csv'));
save(fullfile(this_dir, 'transition_re_political_path_results.mat'), ...
    'summary', 'periods', 'results', 'demographic_path', 'price_path_guess', 'guess_source');
end

function params = default_political_path_params_local()
params = struct();
params.max_iter = 1;
params.tol = 1e-4;
params.damping = 0.25;
params.max_update_frac = 0.10;
params.smoothing_weight = 5.00;
params.terminal_anchor_weight = 0.50;
params.targeted_correction_weight = 0.35;
params.max_targeted_periods = 3;
params.target_block_half_width = 1;
params.line_search_scales = [0.01, 0.02, 0.05];
params.update_scheme = 'sequential_blocks';
params.transition_policy_mode = 'full_backward';
params.terminal_price_rule = 'flat_tail';
params.terminal_reference_mode = 'path_end_price';
params.compute_political_path = true;
params.save_political_details = false;
params.save_period_details = false;
params.coalition_params = struct();
end

function demographic_path_k = truncate_demographic_path_local(demographic_path_full, k)
demographic_path_k = demographic_path_full;
fields = fieldnames(demographic_path_full);
for i = 1:numel(fields)
    field_name = fields{i};
    value = demographic_path_full.(field_name);
    if isnumeric(value)
        if isvector(value) && numel(value) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        elseif ismatrix(value) && size(value, 1) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        else
            demographic_path_k.(field_name) = value;
        end
    else
        demographic_path_k.(field_name) = value;
    end
end
demographic_path_k.description = sprintf('%s Truncated to first %d periods for the political-path workflow.', ...
    demographic_path_full.description, k);
end

function idx = argmax_abs_local(x)
[~, idx] = max(abs(x(:)));
end
