function summary = run_transition_re_policy_bridge_floor_sweep(floor_grid)
% Sweep a floor on the by-period-price policy bridge over the full 2010-2018
% horizon to locate the threshold where current-price policy feedback becomes
% numerically well behaved again.

if nargin < 1 || isempty(floor_grid)
    floor_grid = [NaN, 1.80, 1.85, 1.90, 1.95, 2.00];
end

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

demographic_path_full = build_demographic_path_from_age_state_csv(project_root);
T_full = numel(demographic_path_full.periods);
calendar_years = demographic_path_full.periods(:);

[common_guess, guess_source] = load_common_guess(this_dir, T_full);
cases = build_floor_cases(floor_grid);
base_params = default_floor_sweep_params();

summary_rows = repmat(struct( ...
    'case_name', "", ...
    'description', "", ...
    'transition_policy_mode', "", ...
    'policy_reference_mode', "", ...
    'policy_reference_price', NaN, ...
    'policy_reference_price_floor', NaN, ...
    'policy_reference_price_cap', NaN, ...
    'status', "", ...
    'error_message', "", ...
    'iterations_completed', NaN, ...
    'converged', false, ...
    'looks_stable', false, ...
    'residual_norm', NaN, ...
    'max_abs_gap', NaN, ...
    'max_abs_update', NaN, ...
    'accepted_update', "", ...
    'worst_gap_period', NaN, ...
    'worst_excess_demand_period', NaN, ...
    'worst_excess_demand', NaN, ...
    'price_min', NaN, ...
    'price_max', NaN, ...
    'path_span', NaN, ...
    'policy_reference_min_used', NaN, ...
    'policy_reference_max_used', NaN, ...
    'policy_reference_floor_binding_periods', NaN, ...
    'policy_reference_floor_first_binding_period', NaN, ...
    'policy_reference_floor_last_binding_period', NaN, ...
    'warm_start_source', "", ...
    'elapsed_seconds', NaN), numel(cases), 1);

path_rows = repmat(struct( ...
    'case_name', "", ...
    'period_index', NaN, ...
    'calendar_year', NaN, ...
    'final_price', NaN, ...
    'implied_price', NaN, ...
    'policy_reference_price_used', NaN, ...
    'policy_floor_binding', false, ...
    'Hdemand', NaN, ...
    'Hsupply', NaN, ...
    'excess_demand', NaN, ...
    'rent_share', NaN), numel(cases) * T_full, 1);
path_row_idx = 0;

all_results = cell(numel(cases), 1);

fprintf('=== NIMBY RE policy-bridge floor sweep ===\n');
fprintf('Warm start source: %s\n', guess_source);

for i = 1:numel(cases)
    case_spec = cases(i);
    params = base_params;
    params.transition_policy_mode = char(case_spec.transition_policy_mode);
    params.policy_reference_mode = char(case_spec.policy_reference_mode);
    params.policy_reference_price = case_spec.policy_reference_price;
    params.policy_reference_price_floor = case_spec.policy_reference_price_floor;
    params.policy_reference_price_cap = case_spec.policy_reference_price_cap;

    fprintf('\nRunning case %s ...\n', case_spec.case_name);
    case_tic = tic;
    try
        results = solve_transition_re_no_politics(common_guess, demographic_path_full, params);
        elapsed_seconds = toc(case_tic);
        all_results{i} = results;

        iter_idx = results.iterations;
        policy_ref_path = results.policy_reference_price_path_used(:);
        binding_mask = false(size(policy_ref_path));
        if ~isnan(case_spec.policy_reference_price_floor)
            binding_mask = abs(policy_ref_path - case_spec.policy_reference_price_floor) < 1e-10;
        end

        summary_rows(i) = struct( ...
            'case_name', case_spec.case_name, ...
            'description', case_spec.description, ...
            'transition_policy_mode', string(results.params.transition_policy_mode), ...
            'policy_reference_mode', string(results.params.policy_reference_mode), ...
            'policy_reference_price', case_spec.policy_reference_price, ...
            'policy_reference_price_floor', case_spec.policy_reference_price_floor, ...
            'policy_reference_price_cap', case_spec.policy_reference_price_cap, ...
            'status', "ok", ...
            'error_message', "", ...
            'iterations_completed', iter_idx, ...
            'converged', results.converged, ...
            'looks_stable', looks_stable(results, params), ...
            'residual_norm', results.iteration_log(iter_idx).residual_norm, ...
            'max_abs_gap', results.update_diagnostics.max_abs_gap, ...
            'max_abs_update', results.iteration_log(iter_idx).max_abs_update, ...
            'accepted_update', string(results.iteration_log(iter_idx).accepted_update), ...
            'worst_gap_period', results.iteration_log(iter_idx).worst_gap_period, ...
            'worst_excess_demand_period', results.iteration_log(iter_idx).worst_excess_demand_period, ...
            'worst_excess_demand', results.iteration_log(iter_idx).worst_excess_demand, ...
            'price_min', min(results.final_price_path), ...
            'price_max', max(results.final_price_path), ...
            'path_span', max(results.final_price_path) - min(results.final_price_path), ...
            'policy_reference_min_used', min(policy_ref_path), ...
            'policy_reference_max_used', max(policy_ref_path), ...
            'policy_reference_floor_binding_periods', sum(binding_mask), ...
            'policy_reference_floor_first_binding_period', first_true_index(binding_mask), ...
            'policy_reference_floor_last_binding_period', last_true_index(binding_mask), ...
            'warm_start_source', guess_source, ...
            'elapsed_seconds', elapsed_seconds);

        for t = 1:T_full
            path_row_idx = path_row_idx + 1;
            path_rows(path_row_idx) = struct( ...
                'case_name', case_spec.case_name, ...
                'period_index', t, ...
                'calendar_year', calendar_years(t), ...
                'final_price', results.final_price_path(t), ...
                'implied_price', results.implied_price_path(t), ...
                'policy_reference_price_used', policy_ref_path(t), ...
                'policy_floor_binding', binding_mask(t), ...
                'Hdemand', results.Hdemand_path(t), ...
                'Hsupply', results.Hsupply_path(t), ...
                'excess_demand', results.excess_demand_path(t), ...
                'rent_share', results.rent_share_path(t));
        end

        fprintf(['  gap=%.6f residual=%.6f range=[%.4f, %.4f] policy_ref=[%.4f, %.4f] ' ...
            'bindings=%d stable=%d\n'], ...
            summary_rows(i).max_abs_gap, summary_rows(i).residual_norm, ...
            summary_rows(i).price_min, summary_rows(i).price_max, ...
            summary_rows(i).policy_reference_min_used, summary_rows(i).policy_reference_max_used, ...
            summary_rows(i).policy_reference_floor_binding_periods, summary_rows(i).looks_stable);
    catch ME
        elapsed_seconds = toc(case_tic);
        summary_rows(i) = struct( ...
            'case_name', case_spec.case_name, ...
            'description', case_spec.description, ...
            'transition_policy_mode', string(case_spec.transition_policy_mode), ...
            'policy_reference_mode', string(case_spec.policy_reference_mode), ...
            'policy_reference_price', case_spec.policy_reference_price, ...
            'policy_reference_price_floor', case_spec.policy_reference_price_floor, ...
            'policy_reference_price_cap', case_spec.policy_reference_price_cap, ...
            'status', "error", ...
            'error_message', string(ME.message), ...
            'iterations_completed', NaN, ...
            'converged', false, ...
            'looks_stable', false, ...
            'residual_norm', NaN, ...
            'max_abs_gap', NaN, ...
            'max_abs_update', NaN, ...
            'accepted_update', "", ...
            'worst_gap_period', NaN, ...
            'worst_excess_demand_period', NaN, ...
            'worst_excess_demand', NaN, ...
            'price_min', NaN, ...
            'price_max', NaN, ...
            'path_span', NaN, ...
            'policy_reference_min_used', NaN, ...
            'policy_reference_max_used', NaN, ...
            'policy_reference_floor_binding_periods', NaN, ...
            'policy_reference_floor_first_binding_period', NaN, ...
            'policy_reference_floor_last_binding_period', NaN, ...
            'warm_start_source', guess_source, ...
            'elapsed_seconds', elapsed_seconds);
        fprintf('  case failed: %s\n', ME.message);
    end
end

summary = struct2table(summary_rows);
path_table = struct2table(path_rows(1:path_row_idx));

writetable(summary, fullfile(this_dir, 'transition_re_policy_bridge_floor_sweep_summary.csv'));
writetable(path_table, fullfile(this_dir, 'transition_re_policy_bridge_floor_sweep_paths.csv'));
save(fullfile(this_dir, 'transition_re_policy_bridge_floor_sweep_results.mat'), ...
    'summary', 'path_table', 'all_results', 'cases', 'common_guess', 'guess_source');
end

function params = default_floor_sweep_params()
params = struct();
params.max_iter = 25;
params.tol = 1e-4;
params.damping = 0.25;
params.max_update_frac = 0.10;
params.smoothing_weight = 5.00;
params.terminal_anchor_weight = 0.50;
params.targeted_correction_weight = 0.35;
params.max_targeted_periods = 3;
params.target_block_half_width = 1;
params.line_search_scales = [0.01, 0.02, 0.05];
params.update_scheme = 'sequential_blocks';
params.outer_iteration_mode = 'fertility_style';
params.fixed_point_relaxation_weight = 0.10;
params.fixed_point_relaxation_space = 'log';
params.fixed_point_price_min = 0.40;
params.fixed_point_price_max = 5.00;
params.terminal_price_rule = 'flat_tail';
params.terminal_reference_mode = 'fixed_price';
params.terminal_reference_price = 2.0;
params.transition_policy_mode = 'steady_state_by_period_price';
params.policy_reference_mode = 'path_current_prices';
params.policy_reference_price = NaN;
params.policy_reference_price_floor = NaN;
params.policy_reference_price_cap = NaN;
end

function cases = build_floor_cases(floor_grid)
cases = repmat(struct( ...
    'case_name', "", ...
    'description', "", ...
    'transition_policy_mode', "", ...
    'policy_reference_mode', "", ...
    'policy_reference_price', NaN, ...
    'policy_reference_price_floor', NaN, ...
    'policy_reference_price_cap', NaN), numel(floor_grid) + 1, 1);

cases(1) = struct( ...
    'case_name', "steady_state_fixed_price_2_0_benchmark", ...
    'description', "Fixed-price policy bridge benchmark at price 2.0.", ...
    'transition_policy_mode', "steady_state_fixed_price", ...
    'policy_reference_mode', "fixed_price", ...
    'policy_reference_price', 2.0, ...
    'policy_reference_price_floor', NaN, ...
    'policy_reference_price_cap', NaN);

for i = 1:numel(floor_grid)
    floor_value = floor_grid(i);
    if isnan(floor_value)
        case_name = "steady_state_by_period_price_unclipped";
        description = "By-period-price policy bridge with no floor.";
    else
        case_name = sprintf('steady_state_by_period_price_floor_%.2f', floor_value);
        description = sprintf('By-period-price policy bridge with policy-price floor %.2f.', floor_value);
    end

    cases(i + 1) = struct( ...
        'case_name', string(case_name), ...
        'description', string(description), ...
        'transition_policy_mode', "steady_state_by_period_price", ...
        'policy_reference_mode', "path_current_prices", ...
        'policy_reference_price', NaN, ...
        'policy_reference_price_floor', floor_value, ...
        'policy_reference_price_cap', NaN);
end
end

function [common_guess, guess_source] = load_common_guess(this_dir, T_full)
fixed_price_results_path = fullfile(this_dir, 'transition_re_k_step_policy_bridge_steady_state_fixed_price_2_0_results.mat');

if ~isfile(fixed_price_results_path)
    fprintf('Fixed-price policy-bridge ladder result missing. Generating benchmark first ...\n');
    run_transition_re_k_step_policy_bridge_ladder(T_full, 'steady_state_fixed_price_2_0');
end

loaded = load(fixed_price_results_path, 'all_results');
if isfield(loaded, 'all_results') && ~isempty(loaded.all_results) && ...
        numel(loaded.all_results) >= T_full && ~isempty(loaded.all_results{T_full})
    common_guess = loaded.all_results{T_full}.final_price_path(:);
    guess_source = "transition_re_k_step_policy_bridge_steady_state_fixed_price_2_0_results.final_price_path";
    return;
end

fallback_results_path = fullfile(this_dir, 'transition_re_no_politics_results.mat');
if isfile(fallback_results_path)
    loaded = load(fallback_results_path, 'results');
    if isfield(loaded, 'results') && isfield(loaded.results, 'final_price_path') && ...
            numel(loaded.results.final_price_path) == T_full
        common_guess = loaded.results.final_price_path(:);
        guess_source = "transition_re_no_politics_results.final_price_path";
        return;
    end
end

common_guess = 2.0 .* ones(T_full, 1);
guess_source = "flat_2.0";
end

function tf = looks_stable(results, params)
tol = 1e-6;
tf = results.update_diagnostics.max_abs_gap < 0.05 && ...
    min(results.final_price_path) > params.fixed_point_price_min + tol && ...
    max(results.final_price_path) < params.fixed_point_price_max - tol;
end

function idx = first_true_index(mask)
match = find(mask, 1, 'first');
if isempty(match)
    idx = NaN;
else
    idx = match;
end
end

function idx = last_true_index(mask)
match = find(mask, 1, 'last');
if isempty(match)
    idx = NaN;
else
    idx = match;
end
end
