function summary = run_transition_re_k2_bridge_followup()
% Compare simplified terminal-tail bridge objects on the first nontrivial
% bounded-horizon NIMBY RE problem, k = 2.

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

demographic_path_full = build_demographic_path_from_age_state_csv(project_root);
demographic_path_k1 = truncate_demographic_path(demographic_path_full, 1);
demographic_path_k2 = truncate_demographic_path(demographic_path_full, 2);
T_full = numel(demographic_path_full.periods);

anchor_price_path = 2.0 .* ones(T_full, 1);
anchor_source = "flat_2.0";
previous_results_path = fullfile(this_dir, 'transition_re_no_politics_results.mat');
if isfile(previous_results_path)
    loaded = load(previous_results_path, 'results');
    if isfield(loaded, 'results') && isfield(loaded.results, 'final_price_path') && ...
            numel(loaded.results.final_price_path) == T_full
        anchor_price_path = loaded.results.final_price_path(:);
        anchor_source = "transition_re_no_politics_results.final_price_path";
    end
end

base_params = default_bridge_params();

fprintf('=== NIMBY RE k=2 bridge follow-up ===\n');
fprintf('Anchor source: %s\n', anchor_source);
fprintf('Solving k=1 anchor case first ...\n');

k1_tic = tic;
k1_results = solve_transition_re_no_politics(anchor_price_path(1), demographic_path_k1, base_params);
k1_elapsed = toc(k1_tic);
k1_price = k1_results.final_price_path(1);
k2_guess = [k1_price; anchor_price_path(2)];
k2_guess_source = sprintf('k1_final_plus_%s_second_period', anchor_source);

fprintf('k=1 anchor solved in %.2fs at price %.6f\n', k1_elapsed, k1_price);
fprintf('k=2 warm start: [%.6f, %.6f]\n', k2_guess(1), k2_guess(2));

cases = [ ...
    struct( ...
        'case_name', "path_end_price_tail", ...
        'terminal_reference_mode', "path_end_price", ...
        'terminal_reference_price', NaN, ...
        'description', "Current default: terminal steady state priced at period-2 price."), ...
    struct( ...
        'case_name', "initial_path_price_tail", ...
        'terminal_reference_mode', "initial_path_price", ...
        'terminal_reference_price', NaN, ...
        'description', "Simplified bridge: terminal steady state fixed at period-1 price."), ...
    struct( ...
        'case_name', "fixed_price_2_0_tail", ...
        'terminal_reference_mode', "fixed_price", ...
        'terminal_reference_price', 2.0, ...
        'description', "Simplified bridge: terminal steady state fixed at the baseline price 2.0.") ...
    ];

summary_rows = repmat(struct( ...
    'case_name', "", ...
    'description', "", ...
    'terminal_reference_mode', "", ...
    'terminal_reference_price', NaN, ...
    'terminal_reference_price_used', NaN, ...
    'status', "", ...
    'iterations_completed', NaN, ...
    'converged', false, ...
    'residual_norm', NaN, ...
    'max_abs_gap', NaN, ...
    'max_abs_update', NaN, ...
    'accepted_update', "", ...
    'worst_gap_period', NaN, ...
    'worst_excess_demand_period', NaN, ...
    'worst_excess_demand', NaN, ...
    'start_price_1', NaN, ...
    'start_price_2', NaN, ...
    'final_price_1', NaN, ...
    'final_price_2', NaN, ...
    'implied_price_1', NaN, ...
    'implied_price_2', NaN, ...
    'Hdemand_1', NaN, ...
    'Hdemand_2', NaN, ...
    'Hsupply_1', NaN, ...
    'Hsupply_2', NaN, ...
    'excess_demand_1', NaN, ...
    'excess_demand_2', NaN, ...
    'warm_start_source', "", ...
    'elapsed_seconds', NaN), numel(cases), 1);
all_results = cell(numel(cases), 1);

for i = 1:numel(cases)
    case_spec = cases(i);
    params = base_params;
    params.terminal_reference_mode = char(case_spec.terminal_reference_mode);
    if strcmpi(case_spec.terminal_reference_mode, "fixed_price")
        params.terminal_reference_price = case_spec.terminal_reference_price;
    end

    fprintf('\nRunning case %s ...\n', case_spec.case_name);
    case_tic = tic;
    try
        results = solve_transition_re_no_politics(k2_guess, demographic_path_k2, params);
        elapsed_seconds = toc(case_tic);
        all_results{i} = results;

        iter_idx = results.iterations;
        summary_rows(i) = struct( ...
            'case_name', case_spec.case_name, ...
            'description', case_spec.description, ...
            'terminal_reference_mode', string(results.params.terminal_reference_mode), ...
            'terminal_reference_price', case_spec.terminal_reference_price, ...
            'terminal_reference_price_used', results.terminal_reference_price_used, ...
            'status', "ok", ...
            'iterations_completed', iter_idx, ...
            'converged', results.converged, ...
            'residual_norm', results.iteration_log(iter_idx).residual_norm, ...
            'max_abs_gap', results.update_diagnostics.max_abs_gap, ...
            'max_abs_update', results.iteration_log(iter_idx).max_abs_update, ...
            'accepted_update', string(results.iteration_log(iter_idx).accepted_update), ...
            'worst_gap_period', results.iteration_log(iter_idx).worst_gap_period, ...
            'worst_excess_demand_period', results.iteration_log(iter_idx).worst_excess_demand_period, ...
            'worst_excess_demand', results.iteration_log(iter_idx).worst_excess_demand, ...
            'start_price_1', k2_guess(1), ...
            'start_price_2', k2_guess(2), ...
            'final_price_1', results.final_price_path(1), ...
            'final_price_2', results.final_price_path(2), ...
            'implied_price_1', results.implied_price_path(1), ...
            'implied_price_2', results.implied_price_path(2), ...
            'Hdemand_1', results.Hdemand_path(1), ...
            'Hdemand_2', results.Hdemand_path(2), ...
            'Hsupply_1', results.Hsupply_path(1), ...
            'Hsupply_2', results.Hsupply_path(2), ...
            'excess_demand_1', results.excess_demand_path(1), ...
            'excess_demand_2', results.excess_demand_path(2), ...
            'warm_start_source', k2_guess_source, ...
            'elapsed_seconds', elapsed_seconds);

        fprintf('  gap=%.6f implied_p2=%.6f final_p2=%.6f excess2=%.6f\n', ...
            summary_rows(i).max_abs_gap, summary_rows(i).implied_price_2, ...
            summary_rows(i).final_price_2, summary_rows(i).excess_demand_2);
    catch ME
        elapsed_seconds = toc(case_tic);
        summary_rows(i) = struct( ...
            'case_name', case_spec.case_name, ...
            'description', case_spec.description, ...
            'terminal_reference_mode', string(case_spec.terminal_reference_mode), ...
            'terminal_reference_price', case_spec.terminal_reference_price, ...
            'terminal_reference_price_used', NaN, ...
            'status', "error", ...
            'iterations_completed', NaN, ...
            'converged', false, ...
            'residual_norm', NaN, ...
            'max_abs_gap', NaN, ...
            'max_abs_update', NaN, ...
            'accepted_update', "", ...
            'worst_gap_period', NaN, ...
            'worst_excess_demand_period', NaN, ...
            'worst_excess_demand', NaN, ...
            'start_price_1', k2_guess(1), ...
            'start_price_2', k2_guess(2), ...
            'final_price_1', NaN, ...
            'final_price_2', NaN, ...
            'implied_price_1', NaN, ...
            'implied_price_2', NaN, ...
            'Hdemand_1', NaN, ...
            'Hdemand_2', NaN, ...
            'Hsupply_1', NaN, ...
            'Hsupply_2', NaN, ...
            'excess_demand_1', NaN, ...
            'excess_demand_2', NaN, ...
            'warm_start_source', k2_guess_source, ...
            'elapsed_seconds', elapsed_seconds);
        save(fullfile(this_dir, 'transition_re_k2_bridge_results.mat'), ...
            'summary_rows', 'all_results', 'cases', 'anchor_source', 'anchor_price_path', ...
            'k1_results', 'k1_elapsed', 'k2_guess', 'k2_guess_source', 'ME');
        rethrow(ME);
    end
end

summary = struct2table(summary_rows);
writetable(summary, fullfile(this_dir, 'transition_re_k2_bridge_summary.csv'));
save(fullfile(this_dir, 'transition_re_k2_bridge_results.mat'), ...
    'summary', 'all_results', 'cases', 'anchor_source', 'anchor_price_path', ...
    'k1_results', 'k1_elapsed', 'k2_guess', 'k2_guess_source');
end

function params = default_bridge_params()
params = struct();
params.max_iter = 25;
params.tol = 1e-4;
params.damping = 0.25;
params.max_update_frac = 0.10;
params.smoothing_weight = 5.00;
params.terminal_anchor_weight = 0.50;
params.targeted_correction_weight = 0.35;
params.max_targeted_periods = 3;
params.target_block_half_width = 1;
params.line_search_scales = [0.01, 0.02, 0.05];
params.update_scheme = 'sequential_blocks';
params.outer_iteration_mode = 'fertility_style';
params.fixed_point_relaxation_weight = 0.10;
params.fixed_point_relaxation_space = 'log';
params.fixed_point_price_min = 0.40;
params.fixed_point_price_max = 5.00;
params.terminal_price_rule = 'flat_tail';
params.terminal_reference_mode = 'path_end_price';
params.terminal_reference_price = NaN;
end

function demographic_path_k = truncate_demographic_path(demographic_path_full, k)
demographic_path_k = demographic_path_full;
fields = fieldnames(demographic_path_full);
for i = 1:numel(fields)
    field_name = fields{i};
    value = demographic_path_full.(field_name);
    if isnumeric(value)
        if isvector(value) && numel(value) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        elseif ismatrix(value) && size(value, 1) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        else
            demographic_path_k.(field_name) = value;
        end
    else
        demographic_path_k.(field_name) = value;
    end
end
demographic_path_k.description = sprintf('%s Truncated to first %d periods for the k=2 bridge workflow.', ...
    demographic_path_full.description, k);
end
