function [summary, periods, base_results] = run_transition_re_joint_price_vote_weight_sweep(max_k, vote_weights)
% Sweep the bounded joint political update weight while holding the
% underlying housing solve fixed.

if nargin < 1 || isempty(max_k)
    max_k = 4;
end
if nargin < 2 || isempty(vote_weights)
    vote_weights = [0.0; 0.0005; 0.0010; 0.0020; 0.0050];
end

vote_weights = vote_weights(:);

this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
project_root = fileparts(fileparts(this_dir));
baseline_dir = fullfile(project_root, 'code', 'steadystate');

addpath(baseline_dir);
addpath(this_dir);

demographic_path_full = build_demographic_path_from_age_state_csv(project_root);
T_full = numel(demographic_path_full.periods);
max_k = min(max(1, round(max_k)), T_full);
demographic_path = truncate_demographic_path_local(demographic_path_full, max_k);

price_path_guess = 2.0 .* ones(max_k, 1);
guess_source = "flat_2.0";
previous_results_path = fullfile(this_dir, 'transition_re_no_politics_results.mat');
if isfile(previous_results_path)
    loaded = load(previous_results_path, 'results');
    if isfield(loaded, 'results') && isfield(loaded.results, 'final_price_path') && ...
            numel(loaded.results.final_price_path) >= max_k
        price_path_guess = loaded.results.final_price_path(1:max_k);
        guess_source = "transition_re_no_politics_results.final_price_path_prefix";
    end
end

params = default_joint_params_local();

fprintf('=== Joint price-vote weight sweep ===\n');
fprintf('Periods: %d\n', max_k);
fprintf('Weights: %s\n', mat2str(vote_weights'));
fprintf('Guess source: %s\n', guess_source);

solve_tic = tic;
base_results = solve_transition_re_no_politics(price_path_guess, demographic_path, params);
solve_elapsed_seconds = toc(solve_tic);

housing_candidate_price = base_results.final_price_path(:);
weighted_vote_share = base_results.political.weighted_vote_share_path(:);
equal_weight_vote = base_results.political.equal_weight_vote_path(:);
weighted_vote = base_results.political.weighted_vote_path(:);
implied_price = base_results.implied_price_path(:);
excess_demand = base_results.excess_demand_path(:);

n_weights = numel(vote_weights);
summary_rows = repmat(struct( ...
    'vote_weight', NaN, ...
    'guess_source', "", ...
    'solve_elapsed_seconds', NaN, ...
    'residual_norm', NaN, ...
    'max_abs_gap', NaN, ...
    'max_abs_weighted_vote', NaN, ...
    'max_abs_weighted_vote_share', NaN, ...
    'mean_weighted_vote_share', NaN, ...
    'price_min', NaN, ...
    'price_max', NaN, ...
    'mean_adjustment', NaN, ...
    'max_abs_adjustment', NaN, ...
    'conflict_period_count', NaN, ...
    'conflict_period_share', NaN), n_weights, 1);

period_rows = repmat(struct( ...
    'vote_weight', NaN, ...
    'period_index', NaN, ...
    'year', NaN, ...
    'price_guess', NaN, ...
    'housing_candidate_price', NaN, ...
    'implied_price', NaN, ...
    'weighted_vote_share', NaN, ...
    'adjusted_price', NaN, ...
    'adjustment', NaN, ...
    'equal_weight_vote', NaN, ...
    'weighted_vote', NaN, ...
    'excess_demand', NaN, ...
    'housing_push_up', false, ...
    'political_push_down', false, ...
    'conflict', false), n_weights * max_k, 1);

row_idx = 0;
for iw = 1:n_weights
    vote_weight = vote_weights(iw);
    adjusted_price = housing_candidate_price .* exp(vote_weight .* weighted_vote_share);
    adjustment = adjusted_price - housing_candidate_price;
    housing_push_up = implied_price > price_path_guess + 1e-12;
    political_push_down = weighted_vote_share < -1e-12;
    conflict = housing_push_up & political_push_down;

    summary_rows(iw) = struct( ...
        'vote_weight', vote_weight, ...
        'guess_source', guess_source, ...
        'solve_elapsed_seconds', solve_elapsed_seconds, ...
        'residual_norm', base_results.iteration_log(base_results.iterations).residual_norm, ...
        'max_abs_gap', base_results.update_diagnostics.max_abs_gap, ...
        'max_abs_weighted_vote', max(abs(weighted_vote)), ...
        'max_abs_weighted_vote_share', max(abs(weighted_vote_share)), ...
        'mean_weighted_vote_share', mean(weighted_vote_share), ...
        'price_min', min(adjusted_price), ...
        'price_max', max(adjusted_price), ...
        'mean_adjustment', mean(adjustment), ...
        'max_abs_adjustment', max(abs(adjustment)), ...
        'conflict_period_count', sum(conflict), ...
        'conflict_period_share', mean(conflict));

    for t = 1:max_k
        row_idx = row_idx + 1;
        period_rows(row_idx) = struct( ...
            'vote_weight', vote_weight, ...
            'period_index', t, ...
            'year', demographic_path.years(t), ...
            'price_guess', price_path_guess(t), ...
            'housing_candidate_price', housing_candidate_price(t), ...
            'implied_price', implied_price(t), ...
            'weighted_vote_share', weighted_vote_share(t), ...
            'adjusted_price', adjusted_price(t), ...
            'adjustment', adjustment(t), ...
            'equal_weight_vote', equal_weight_vote(t), ...
            'weighted_vote', weighted_vote(t), ...
            'excess_demand', excess_demand(t), ...
            'housing_push_up', housing_push_up(t), ...
            'political_push_down', political_push_down(t), ...
            'conflict', conflict(t));
    end
end

summary = struct2table(summary_rows);
periods = struct2table(period_rows(1:row_idx));
writetable(summary, fullfile(this_dir, 'transition_re_joint_price_vote_weight_sweep_summary.csv'));
writetable(periods, fullfile(this_dir, 'transition_re_joint_price_vote_weight_sweep_periods.csv'));
save(fullfile(this_dir, 'transition_re_joint_price_vote_weight_sweep_results.mat'), ...
    'summary', 'periods', 'base_results', 'demographic_path', 'price_path_guess', 'vote_weights', ...
    'housing_candidate_price', 'weighted_vote_share');
end

function params = default_joint_params_local()
params = struct();
params.max_iter = 1;
params.tol = 1e-4;
params.damping = 0.25;
params.max_update_frac = 0.10;
params.smoothing_weight = 5.00;
params.terminal_anchor_weight = 0.50;
params.targeted_correction_weight = 0.35;
params.max_targeted_periods = 3;
params.target_block_half_width = 1;
params.line_search_scales = [0.01, 0.02, 0.05];
params.update_scheme = 'sequential_blocks';
params.transition_policy_mode = 'full_backward';
params.terminal_price_rule = 'flat_tail';
params.terminal_reference_mode = 'path_end_price';
params.compute_political_path = true;
params.save_political_details = false;
params.save_period_details = false;
params.coalition_params = struct();
end

function demographic_path_k = truncate_demographic_path_local(demographic_path_full, k)
demographic_path_k = demographic_path_full;
fields = fieldnames(demographic_path_full);
for i = 1:numel(fields)
    field_name = fields{i};
    value = demographic_path_full.(field_name);
    if isnumeric(value)
        if isvector(value) && numel(value) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        elseif ismatrix(value) && size(value, 1) == numel(demographic_path_full.periods)
            demographic_path_k.(field_name) = value(1:k, :);
        else
            demographic_path_k.(field_name) = value;
        end
    else
        demographic_path_k.(field_name) = value;
    end
end
demographic_path_k.description = sprintf('%s Truncated to first %d periods for the vote-weight sweep.', ...
    demographic_path_full.description, k);
end
